((twod, k) => { if(window[k]) return; window[k] = true;(()=>{"use strict";function e(e,t,n,o,s,r,i){try{var c=r(e,i),a=Ut(c,"value")}catch(e){return void n(e)}Ut(c,"done")?t(a):cn(new an((e=>e(a))),o,s)}function t(t){const n=function(){var n=this,o=arguments;return new an((function(s,r){function i(t){e(a,s,r,i,c,dn,t)}function c(t){e(a,s,r,i,c,ln,t)}var a=Ct(t,n,o);i(void 0)}))};return At(n,"apply",(function(e,t){return Ct(n,e,t)})),n}function n(e,t){let n,o=!0;return"boolean"==typeof e?(o=e,n=t):n=e,Fn((e=>{const t=bn(bt.document)
;"interactive"==t||"complete"==t?(n&&n(),e()):Bn.addEventListener("DOMContentLoaded",(()=>{n&&n(),e()}),$t({capture:o,once:!0}))}))}const o=["chrome"],s=e=>{const t=Object.call,n=t.bind(t),o=Object.assign,s=Object.getOwnPropertyDescriptor,r=Object.getPrototypeOf,i=e=>o({__proto__:null},e),c=r(function*(){}()),a=r(Uint8Array.prototype);return i({sourceWindow:e,cSO:i,F_c:n,F_a:Object.apply,F_b:Object.bind,F_tS:Function.toString,A_fE:[].forEach,A_so:[].some,A_sh:[].shift,A_j:[].join,
A_iO:[].indexOf,A_iA:Array.isArray,O_a:o,O_k:Object.keys,O_v:Object.values,O_dP:Object.defineProperties,O_dPy:Object.defineProperty,O_hOP:Object.hasOwnProperty,O_gOPN:Object.getOwnPropertyNames,O_gOPD:s,O_gOPDs:Object.getOwnPropertyDescriptors,O_gPO:r,O_tS:{}.toString,J_p:JSON.parse,J_s:JSON.stringify,M_f:Math.floor,M_r:Math.random,M_m:Math.max,M_mi:Math.min,N_tS:(0).toString,N_MSI:Number.MAX_SAFE_INTEGER,P_t:Promise.prototype.then,P_c:Promise.prototype.catch,P_co:Promise.prototype.constructor,
G_n:c.next,G_t:c.throw,R_rABS:FileReader.prototype.readAsBinaryString,R_rAT:FileReader.prototype.readAsText,R_r:s(FileReader.prototype,"result").get,R_enq:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.enqueue:null,R_cl:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.close:null,S_fCC:String.fromCharCode,S_sl:"".slice,S_su:"".substr,S_sp_nr:"".split,S_iO:"".indexOf,S_tr:"".trim,S_r_nr:"".replace,S_rA_nr:"".replaceAll,
S_cCA:"".charCodeAt,S_tLC:"".toLowerCase,S_tUC:"".toUpperCase,Y_tST:Symbol.toStringTag,Y_unsc:Symbol.unscopables,USP_tS:URLSearchParams.prototype.toString,D_pFS:DOMParser.prototype.parseFromString,U_cOU:URL.createObjectURL,U_rOU:URL.revokeObjectURL,X_o:XMLHttpRequest.prototype.open,X_pSD:XMLHttpRequest.prototype.DONE,X_pSH:XMLHttpRequest.prototype.HEADERS_RECEIVED,X_pSL:XMLHttpRequest.prototype.LOADING,X_pSO:XMLHttpRequest.prototype.OPENED,X_pSU:XMLHttpRequest.prototype.UNSENT,
X_s:XMLHttpRequest.prototype.send,D_n:Date.now,I_tS:e=>""+e,E_r:Element.prototype.remove,E_s:Element.prototype.setAttribute,E_rA:Element.prototype.removeAttribute,D_cS:s(Document.prototype,"currentScript").get,D_gRS:s(Document.prototype,"readyState").get,D_cE:Document.prototype.createElementNS,D_gEBT:Document.prototype.getElementsByTagName,M_rT:s(MouseEvent.prototype,"relatedTarget").get,C_d:s(CustomEvent.prototype,"detail").get,P_p:s(PageTransitionEvent.prototype,"persisted").get,
C_pA:CustomEvent.prototype.AT_TARGET,M_d:MutationObserver.prototype.disconnect,W_aEL:addEventListener,W_rEL:removeEventListener,TA_b:s(a,"buffer").get,TA_sa:Uint8Array.prototype.subarray,parseInt,parseFloat,CustomEvent,CompositionEvent,KeyboardEvent,MouseEvent,MutationObserver,console:Object.assign({},console),Error,Uint8Array,Blob,ReadableStream,Number,String,Proxy,Window,FileReader,DOMParser,XMLHttpRequest,Function,RegExp,Promise,encodeURIComponent,decodeURIComponent,encodeURI,decodeURI,
escape,unescape,atob,btoa,setTimeout,clearTimeout,setInterval,clearInterval,postMessage,dispatchEvent,alert,prompt,confirm,close,getElementById:e.Document.prototype.getElementById,createEvent:e.Document.prototype.createEvent,createElement:e.Document.prototype.createElement})},r="vault"in twod;if(r&&void 0===twod.vault)throw"Invalid vault"
;const i=twod.vault=twod.vault||s(twod.unsafeWindow),{cSO:c,F_c:a,F_a:d,F_b:l,F_tS:u,A_fE:p,A_so:g,A_sh:m,A_j:f,A_iO:h,A_iA:v,O_a:b,O_k:_,O_v:w,O_dP:y,O_dPy:M,O_hOP:L,O_gOPN:E,O_gOPD:I,O_gOPDs:S,O_gPO:O,O_tS:x,J_p:D,J_s:R,M_f:j,M_r:P,M_m:C,M_mi:$,N_tS:A,N_MSI:T,P_t:U,P_c:k,P_co:B,G_n:F,G_t:X,R_rABS:N,R_rAT:q,R_r:W,R_enq:H,R_cl:G,S_fCC:J,S_sl:K,S_su:z,S_iO:Y,S_sp_nr:V,S_tr:Z,S_rA_nr:Q,S_cCA:ee,S_tLC:te,S_tUC:ne,Y_tST:oe,Y_unsc:se,D_pFS:re,D_cS:ie,D_gRS:ce,D_cE:ae,D_gEBT:de,E_r:le,E_s:ue,E_rA:pe,C_pA:ge,M_d:me,C_d:fe,P_p:he,M_rT:ve,U_cOU:be,U_rOU:_e,USP_tS:we,X_o:ye,X_s:Me,X_pSD:Le,X_pSH:Ee,X_pSL:Ie,X_pSO:Se,X_pSU:Oe,D_n:xe,I_tS:De,W_aEL:Re,W_rEL:je,TA_b:Pe,TA_sa:Ce,parseInt:$e,parseFloat:Ae,console:Te,encodeURIComponent:Ue,decodeURIComponent:ke,encodeURI:Be,decodeURI:Fe,escape:Xe,unescape:Ne,atob:qe,btoa:We,postMessage:He,dispatchEvent:Ge,alert:Je,prompt:Ke,confirm:ze,close:Ye,getElementById:Ve,createEvent:Ze,createElement:Qe,CustomEvent:et,CompositionEvent:tt,KeyboardEvent:nt,MouseEvent:ot,MutationObserver:st,Uint8Array:rt,FileReader:it,DOMParser:ct,XMLHttpRequest:at,Function:dt,RegExp:lt,Blob:ut,ReadableStream:pt,Number:gt,String:mt,Proxy:ft,Window:ht}=i,vt=twod,{unsafeWindow:bt,unsafeThis:_t}=vt,wt=a,yt=d,Mt=_,Lt=w,Et=b,It=M,St=E,Ot=I,xt=O,Dt=v,Rt=P,jt=C,Pt=$,Ct=(e,t,n)=>wt(yt,e,t,n),$t=c,At=(e,t,n)=>(It(e,t,$t({
value:n,configurable:!0,enumerable:!0,writable:!0})),e),Tt=(e,t)=>Vt(e,t)?e[t]:void 0,Ut=(e,t)=>{const n=Ot(e,t);return n?$t(n).value:void 0},kt=(e,t)=>{const n=(e,t,o)=>{const s=Ot(e,t),r=s?$t(s):void 0;let i;return r?r.enumerable?r.value:void 0:--o>=0&&(i=xt(e))?n(i,t,o):void 0};return n(e,t,5)},Bt=e=>{const t=(t,...n)=>Ct(e,t,n);return At(t,"wrappedJSObject",e),t},Ft=()=>e=>Bt(e),Xt=Bt(l),Nt=D,qt=Ft()(g),Wt=Ft()(m),Ht=(e,t)=>{const n=[];return Yt(e,(e=>{t(e)&&Kt(n,e)})),n},Gt=(e,t,n)=>{
const o=e.length;let s=t||0;if(s>=o)return[];s<0&&(s=jt(0,o+s));let r=void 0===n?o:n;r<0&&(r=jt(0,o+r)),r>o&&(r=o);const i=$t({});for(let t=s;t<r;t++)i[t]=Ut(e,t);return Lt(i)},Jt=Ft()(f),Kt=(e,t)=>{let n=e.length||0;return At(e,n,t),n++,e.length=n},zt=Ft()(h),Yt=Ft()(p),Vt=Ft()(L),Zt=Ft()(V),Qt=Ft()(K),en=Bt(x),tn=xt({}),nn=e=>{const t=$t(e),n=St(t);for(let e=0;e<n.length;e++){const o=n[e],s=t[o];null!==s&&"object"==typeof s&&xt(s)===tn&&(t[o]=nn(s))}return t},on=e=>{const t=Zt(en(e)," ")
;return Qt(Jt(Gt(t,1)," "),0,-1)},sn=Ft()(u),rn=Ft()(A),cn=Ft()(U),an=(Ft()(k),Xt(B,xt((async()=>{})()))),dn=Ft()(F),ln=Ft()(X),un=Ft()(N),pn=(Ft()(q),Ft()(W)),gn=(H&&Ft()(H),G&&Ft()(G),J),mn=Ft()(z),fn=Ft()(Y),hn=(Ft()(Z),Ft()(Q||function(e,t){return Jt(Zt(this,e),t)}),Ft()(ee)),vn=Ft()(te),bn=(Ft()(ne),Bt(re),Bt(ie),Bt(ce)),_n=Bt(ae),wn=Bt(de),yn=(Bt(le),Bt(ue),Bt(pe),Bt(ve)),Mn=Bt(fe),Ln=Bt(he),En=me?Ft()(me):me,In=be,Sn=_e,On=(Bt(we),Bt(Pe)),xn=(Ft()(Ce),Ft()(ye),Ft()(Me),
xe),Dn=et,Rn=ot,jn=rt,Pn=st,Cn=ut,$n=lt,An=function(e,t){return Ut(e,t)},Tn=$t({addEventListener:!1,Array:!0,Blob:!0,close:!1,CustomEvent:!0,Date:!0,DOMParser:!0,Error:!0,Event:!0,FileReader:!0,KeyboardEvent:!0,location:!0,Math:!0,MouseEvent:!0,Number:!0,Object:!0,ReadableStream:!0,removeEventListener:!1,Uint8Array:!0,XMLHttpRequest:!0}),Un=((()=>{const e=$t({getElementById:Ve,createEvent:Ze,createElement:Qe,dispatchEvent:Ge,addEventListener,removeEventListener}),t=$t({});Yt(Mt(e),(n=>{try{
const o=e[n];t[n]=function(...e){return Ct(o,bt.document,e)}}catch(e){t[n]=((e,t)=>{if(kn.error(`Tampermonkey sandbox preparation ${t?"("+t+") ":""}failed. This usually is caused by a third-party extension.`,e),t)return()=>{}})(e,`document.${n}`)}}))})(),$t({top:!0,location:!0}));twod.bridges=twod.bridges||$t({});const kn=twod.console=twod.console||$t({}),Bn=$t({addEventListener:Xt(Re,bt),removeEventListener:Xt(je,bt)});Yt(Mt(Un),(async e=>{if(!Bn[e])try{const t=bt[e];if(null==t)return;Bn[e]=t
}catch(e){}})),Yt(Mt(Tn),(async e=>{if(!Bn[e])try{let t=Ut(bt,e);if(void 0===t&&(_t===bt||void 0===(t=Ut(_t,e))))return;const n=Tn[e];Bn[e]=!1===n&&"function"==typeof t?Xt(t,_t):t}catch(e){}}));const Fn=e=>{let t,n=[],o=!1;e((e=>{if(!o){if(n.length){const t=n;n=[],Yt(t,(t=>t(e)))}else t=e;o=!0}}));const s=$t({then:e=>(o?e(t):Kt(n,e),s)});return s},Xn=()=>rn(xn()+19831206*Rt()+1,36),Nn=function(){var e=t((function*(e){yield null,e()}));return function(t){return e.apply(this,arguments)}
}(),qn=(()=>{const{console:e,bridges:t}=twod,n=$t({});let o;const s=(t,o,s,i)=>{let c,a=[],d=[],l=[],u=[];const p=()=>{d=[],l=[],u=[],h(),y=null,delete n[o]},g=e=>{t.send("port.message",$t({response_id:o,value:e}))},m=e=>{i&&"messageId"in e&&Kt(a,e),g(e)},f=(e,t=!0)=>{c=e,t&&g(e)},h=()=>{c=void 0},v=$t({addListener:e=>{Kt(d,e)}}),b=$t({addListener:e=>{Kt(l,e)}}),_=$t({addListener:e=>{Kt(u,e)}}),w=()=>{p(),t.send("port.message",$t({response_id:o,disconnect:!0}))};let y=$t(s?{postMessage:m,
connectMessage:f,stopReconnecting:h,onMessage:v,onDisconnect:b,onReconnect:_,disconnect:w}:{postMessage:m,onMessage:v,onDisconnect:b,disconnect:w});return n[o]=$t({message:t=>{if(i&&(e=>"ack"in e)(t)){const{messageId:n}=t;(t=>{if(!t)return void e.warn("PortMessaging: no message id in ack message");if(c&&c.messageId===t)return;let n=-1;qt(a,((e,o)=>e.messageId===t&&(n=o,!0))),-1!==n?(Yt(Gt(a,0,n),(t=>e.warn(`PortMessaging: message ${t.messageId} was not ack'ed!`,t))),
a=Gt(a,n+1)):e.warn(`PortMessaging: no one is waiting for ${t}`)})(n)}d&&Yt(d,(e=>e(t)))},disconnect:()=>{if(c&&s)return r(s,o),f(c),i&&Yt(a,(e=>g(e))),void(u.length&&Yt(u,(e=>e())));l.length&&Yt(l,(e=>e())),p()}}),y},r=(e,n)=>{t.first.send("port.message",$t({response_id:n,connect:!0,destination:e}))};return $t({message:(t,r)=>{let i;if(t.connect){if(!t.destination||!t.response_id)throw"invalid message";o&&o(t.destination,s(r,t.response_id))}else{if(!t.response_id)throw"invalid message"
;if(!(i=n[t.response_id]))return void e.warn("ports: unknown id",t.response_id,t);t.disconnect?i.disconnect():i.message(t.value)}},connect:function(e,n,o){const i=Xn();return r(e,i),s(t.first,i,n?e:void 0,o)},onConnect:$t({addListener:e=>{o=e}})})})(),{setInterval:Wn,setTimeout:Hn,clearInterval:Gn,clearTimeout:Jn,console:Kn,cloneInto:zn,exportFunction:Yn,createObjectIn:Vn,btoa:Zn}=bt,Qn=Object.assign({},Kn),eo=Wn.bind(bt),to=Hn.bind(bt),no=Gn.bind(bt),oo=(Jn.bind(bt),
_t==bt.top),{arrayBuffer:so,blob:ro}=bt.Response.prototype,{arrayBuffer:io}=bt.Blob.prototype,{then:co}=bt.Promise.prototype,{fetch:ao,location:lo,document:uo,Response:po}=bt,go=Bt(so),mo=Bt(ro),fo=Bt(io),ho=zn,vo=($t({encode:e=>Ne(Ue(e)),decode:e=>ke(Xe(e))}),$t({encode:e=>{let t="";for(let n=0;n<e.length;n++)t+=gn(255&hn(e,n));return We(t)},decode:e=>qe(e)})),bo=e=>{const t=new jn(e.length);for(let n=0;n<e.length;n++)t[n]=hn(e,n);return On(t)},_o=e=>{let t;const n=Zt(e,","),o=An(n,0),s=An(n,1)
;t=-1!=fn(o,"base64")?qe(s):Ne(s);const r=An(Zt(o,":"),1),i=An(Zt(r,";"),0);return new Cn([bo(t)],$t({type:i}))},wo=(e,t)=>{const n=_n(bt.document,"http://www.w3.org/1999/xhtml",e);return"string"==typeof t?n.append(t):t&&Yt(Mt(t),(e=>{"textContent"==e?n.textContent=t[e]:n.setAttribute(e,t[e])})),n},yo=e=>{const t=bt.document;if(t.body||"text/xml"==t.contentType)e();else{let t=!1;const o=new Pn((()=>{t=!0,yo(e),(En||(e=>e.disconnect()))(o)}));o.observe(bt.document,$t({childList:!0})),n((()=>{
t||((En||(e=>e.disconnect()))(o),e())}))}},Mo=e=>{n((()=>{to((()=>e()),1)}))};let Lo,Eo;const Io=lo.host,So=e=>{"n:"==mn(e,0,2)?Lo=mn(e,2):e&&(Eo=mn(e,2))},Oo=()=>Lo||(Eo?(Lo=(e=>{const t=(e,t)=>e<<t|e>>>32-t,n=(e,t)=>{const n=2147483648&e,o=2147483648&t,s=1073741824&e,r=1073741824&t,i=(1073741823&e)+(1073741823&t);return s&r?2147483648^i^n^o:s|r?1073741824&i?3221225472^i^n^o:1073741824^i^n^o:i^n^o},o=(e,o,s,r,i,c,a)=>(e=n(e,n(n(((e,t,n)=>e&t|~e&n)(o,s,r),i),a)),
n(t(e,c),o)),s=(e,o,s,r,i,c,a)=>(e=n(e,n(n(((e,t,n)=>e&n|t&~n)(o,s,r),i),a)),n(t(e,c),o)),r=(e,o,s,r,i,c,a)=>(e=n(e,n(n(((e,t,n)=>e^t^n)(o,s,r),i),a)),n(t(e,c),o)),i=(e,o,s,r,i,c,a)=>(e=n(e,n(n(((e,t,n)=>t^(e|~n))(o,s,r),i),a)),n(t(e,c),o)),c=e=>{let t,n,o="",s="";for(n=0;n<=3;n++)t=e>>>8*n&255,s="0"+rn(t,16),o+=mn(s,s.length-2,2);return o};let a,d,l,u,p,g,m,f;const h=(e=>{let t;const n=e.length,o=n+8,s=16*((o-o%64)/64+1),r=[];for(let e=0;e<=s-1;e++)Kt(r,0);let i=0,c=0;for(;c<n;)t=(c-c%4)/4,
i=c%4*8,r[t]=r[t]|hn(e,c)<<i,c++;return t=(c-c%4)/4,i=c%4*8,r[t]=r[t]|128<<i,r[s-2]=n<<3,r[s-1]=n>>>29,r})(e);p=1732584193,g=4023233417,m=2562383102,f=271733878;for(let e=0;e<h.length;e+=16)a=p,d=g,l=m,u=f,p=o(p,g,m,f,h[e+0],7,3614090360),f=o(f,p,g,m,h[e+1],12,3905402710),m=o(m,f,p,g,h[e+2],17,606105819),g=o(g,m,f,p,h[e+3],22,3250441966),p=o(p,g,m,f,h[e+4],7,4118548399),f=o(f,p,g,m,h[e+5],12,1200080426),m=o(m,f,p,g,h[e+6],17,2821735955),g=o(g,m,f,p,h[e+7],22,4249261313),
p=o(p,g,m,f,h[e+8],7,1770035416),f=o(f,p,g,m,h[e+9],12,2336552879),m=o(m,f,p,g,h[e+10],17,4294925233),g=o(g,m,f,p,h[e+11],22,2304563134),p=o(p,g,m,f,h[e+12],7,1804603682),f=o(f,p,g,m,h[e+13],12,4254626195),m=o(m,f,p,g,h[e+14],17,2792965006),g=o(g,m,f,p,h[e+15],22,1236535329),p=s(p,g,m,f,h[e+1],5,4129170786),f=s(f,p,g,m,h[e+6],9,3225465664),m=s(m,f,p,g,h[e+11],14,643717713),g=s(g,m,f,p,h[e+0],20,3921069994),p=s(p,g,m,f,h[e+5],5,3593408605),f=s(f,p,g,m,h[e+10],9,38016083),
m=s(m,f,p,g,h[e+15],14,3634488961),g=s(g,m,f,p,h[e+4],20,3889429448),p=s(p,g,m,f,h[e+9],5,568446438),f=s(f,p,g,m,h[e+14],9,3275163606),m=s(m,f,p,g,h[e+3],14,4107603335),g=s(g,m,f,p,h[e+8],20,1163531501),p=s(p,g,m,f,h[e+13],5,2850285829),f=s(f,p,g,m,h[e+2],9,4243563512),m=s(m,f,p,g,h[e+7],14,1735328473),g=s(g,m,f,p,h[e+12],20,2368359562),p=r(p,g,m,f,h[e+5],4,4294588738),f=r(f,p,g,m,h[e+8],11,2272392833),m=r(m,f,p,g,h[e+11],16,1839030562),g=r(g,m,f,p,h[e+14],23,4259657740),
p=r(p,g,m,f,h[e+1],4,2763975236),f=r(f,p,g,m,h[e+4],11,1272893353),m=r(m,f,p,g,h[e+7],16,4139469664),g=r(g,m,f,p,h[e+10],23,3200236656),p=r(p,g,m,f,h[e+13],4,681279174),f=r(f,p,g,m,h[e+0],11,3936430074),m=r(m,f,p,g,h[e+3],16,3572445317),g=r(g,m,f,p,h[e+6],23,76029189),p=r(p,g,m,f,h[e+9],4,3654602809),f=r(f,p,g,m,h[e+12],11,3873151461),m=r(m,f,p,g,h[e+15],16,530742520),g=r(g,m,f,p,h[e+2],23,3299628645),p=i(p,g,m,f,h[e+0],6,4096336452),f=i(f,p,g,m,h[e+7],10,1126891415),
m=i(m,f,p,g,h[e+14],15,2878612391),g=i(g,m,f,p,h[e+5],21,4237533241),p=i(p,g,m,f,h[e+12],6,1700485571),f=i(f,p,g,m,h[e+3],10,2399980690),m=i(m,f,p,g,h[e+10],15,4293915773),g=i(g,m,f,p,h[e+1],21,2240044497),p=i(p,g,m,f,h[e+8],6,1873313359),f=i(f,p,g,m,h[e+15],10,4264355552),m=i(m,f,p,g,h[e+6],15,2734768916),g=i(g,m,f,p,h[e+13],21,1309151649),p=i(p,g,m,f,h[e+4],6,4149444226),f=i(f,p,g,m,h[e+11],10,3174756917),m=i(m,f,p,g,h[e+2],15,718787259),g=i(g,m,f,p,h[e+9],21,3951481745),p=n(p,a),g=n(g,d),
m=n(m,l),f=n(f,u);const v=c(p)+c(g)+c(m)+c(f);return vn(v)})(`${Io}#${Eo}`),Lo):void 0),xo=e=>void 0!==Ut(e,"objUrl"),Do=e=>void 0!==Ut(e,"blob"),Ro=e=>void 0!==Ut(e,"dataUri"),jo=e=>void 0!==e.binary,Po=globalThis;let Co,$o,Ao,To,{chrome:Uo,browser:ko}=Po;Ao=()=>{if(void 0!==Co)return Co;try{const e=navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./);e&&(Co=parseInt(e[2]))}catch(e){}return Co},To=()=>{if(void 0!==$o)return $o;try{$o=-1!=navigator.userAgent.search(/Android|Mobile/)}catch(e){}
return $o},Ao();const Bo=["chrome-extension:"];[].concat(["chrome"]);const Fo=(()=>{const e={getInternalPathRegexp:function(e,t){const n=new RegExp("(\\"+["/",".","+","?","|","(",")","[","]","{","}","\\"].join("|\\")+")","g"),o=Bo[0]+"//"+Fo.id+"/";return new RegExp(o.replace(n,"\\$1")+"([a-zA-Z"+(e?"\\/":"")+"]*)"+(t||"").replace(n,"\\$1"))},getInternalPageRegexp:function(){return Fo.getInternalPathRegexp(!1,".html")},getPlatformInfo:e=>Uo.runtime.getPlatformInfo(e),getBrowserInfo:e=>{e({
name:"Chrome",version:`${Ao()}`,vendor:"unknown"})}};return Object.defineProperty(e,"lastError",{get:()=>Uo.runtime.lastError,enumerable:!0}),Object.defineProperty(e,"id",{get:()=>Uo.runtime.id,enumerable:!0}),Object.defineProperty(e,"short_id",{get:()=>e.id.replace(/[^0-9a-zA-Z]/g,"").substr(0,4),enumerable:!0}),e})(),Xo=(()=>{let e;return Object.defineProperties({},{inIncognitoContext:{get:()=>(void 0===e&&(e=Uo.extension.inIncognitoContext),e),set:t=>{e=t},enumerable:!0},
...Object.getOwnPropertyDescriptors({getURL:function(e){return Uo.runtime.getURL(e)},sendMessage:(e,t)=>Uo.runtime.sendMessage(e,t),onMessage:{addListener:e=>Uo.runtime.onMessage.addListener(e)},connect:e=>Uo.runtime.connect({name:e}),urls:{prepareForReport:function(e){return e}}})})})();t((function*(e,t){yield Uo.offscreen.createDocument({url:"offscreen.html",...e}),t&&t()})),t((function*(e){yield Uo.offscreen.closeDocument(),e&&e()}))
;const No=Uo&&Uo.userScripts&&Uo.userScripts.onBeforeScript?{supported:!0,onBeforeScript:{addListener:e=>Uo.userScripts.onBeforeScript.addListener(e)}}:{supported:!1},qo=({sendPrefix:e,listenPrefix:n,send:o,onMessage:s})=>{if(void 0===o||void 0===s)throw"invalid args";let r,i,c=1;const a=$t({}),d=$t({}),l=e=>{e&&(r=e)},u=e=>{const t=++c;return d[c]=e,t};s(((t,s)=>t==`${n}_${r}`?(t=>{const{m:n,r:s,a:c,n:l}=t;if(a[n]&&(Yt(a[n],(e=>e(c))),delete a[n]),"message.response"==n){
if(null==s)throw"Invalid Message";((e,t)=>{let n;e&&(n=d[e])&&(n(t),delete d[e])})(s,c)}else if(i){const t=s?t=>{o(`${e}_${r}`,$t({m:"message.response",a:t,r:s}))}:()=>{};i($t({method:n,args:c,node:l}),t)}})(s):null));const p=$t({init:(g=t((function*(e){r?l():l(e)})),function(e){return g.apply(this,arguments)}),refresh:()=>null,switchId:e=>{r&&p.cleanup(),l(e)},send:(t,n,s,i)=>Fn((c=>{let a,d;"function"!=typeof s&&null!==s?(a=s,d=i):d=s,o(`${e}_${r}`,$t({m:t,a:n,r:d?u(d):null,n:a})),c()})),
sendToId:(t,n,s)=>{o(`${e}_${t}`,$t({m:n,a:s,r:null}))},once:(e,t)=>{a[e]||(a[e]=[]),Kt(a[e],t)},setMessageListener:e=>{i=e},cleanup:()=>null});var g;return p},Wo=No,Ho=No.supported&&!bt.pagejs;let Go;const Jo=(e,t)=>{try{Go(e),t&&t()}catch(e){t&&t(e.message||e)}},Ko="u"+Xn(),{bridges:zo}=twod;let Yo=[];const Vo=e=>{Wo.onBeforeScript.addListener((o=>{const s=(e,n)=>{Yt(t,(t=>t(e,n)))},r=e=>Kt(n,$t({listener:e,clone:o.export}));It(o.global,"pagejs",$t({set:o.export((t=>{delete o.global.pagejs
;const n=o.metadata,{modes:i,nonce:c}=n;if(c&&So(c),Yt(Yo,(e=>e(t,n))),Yo=[],i.js){const n=$t({unsafeWindow:o.global,unsafeThis:o.global.window,pageWindow:void 0,contextId:Ko,fSend:s,fOnMessage:r,cloneInto:void 0,exportFunction:void 0});t(o.export(n)),zo.js.sendToId(Ko,"commid",$t({id:e}))}})),configurable:!0})),Go=o.global.eval}));const t=[],n=[],o=(e,t)=>{Yt(n,(({listener:n,clone:o})=>n(e,o(t))))},s=e=>Kt(t,e);return $t({createBridge:()=>{const t=qo($t({sendPrefix:"2S",listenPrefix:"2U",
cloneInto:ho,send:o,onMessage:s}));return t.init(e),t}})};let Zo=[],Qo=[];const es=e=>{const t=Xo.connect(e);if(Fo.lastError)return;let n=[];const o=$t({postMessage:e=>t.postMessage(e),onMessage:$t({addListener:e=>t.onMessage.addListener(e)}),onDisconnect:$t({addListener:e=>{Kt(n,e)}}),disconnect:()=>(s(!1),t.disconnect())}),s=e=>{e&&Yt(n,(e=>e())),n=[],Zo=Ht(Zo,(e=>e!==r)),Qo=Ht(Qo,(e=>e!==i))};t.onDisconnect.addListener((()=>s(!0)));const r=()=>{t.disconnect(),Fo.lastError,s(!0)};Kt(Zo,r)
;const i=()=>{t.disconnect(),Fo.lastError};return Kt(Qo,i),o};let ts,ns,os;Bn.addEventListener("pagehide",(e=>{Ln(e)&&Yt(Qo,(e=>e()))})),Bn.addEventListener("pageshow",(e=>{Ln(e)&&Yt(Zo,(e=>e()))}));const{console:ss}=twod,rs=e=>Fn(function(){var n=t((function*(t){const n=e.url;let o,s,r,i;if(!n)return t($t({t:e,c:o}));const c=on(n);if("string"==typeof n){const e=mn(n,0,5);if("blob:"===e)if(os)s=$t({objUrl:$t({url:n})});else{const e=yield ao(n);i=yield mo(e)}else(os||ns)&&"data:"===e?i=_o(n):r=n
}else"Blob"==c||"File"==c?i=n:"ArrayBuffer"==c&&(i=new Cn([n]));if(i)if(ns)s=$t({blob:i});else if(os){const e=In(i);o=()=>Sn(e),s=$t({objUrl:$t({url:e})})}else{const e=yield(a=i,Fn((e=>{const t=new Bn.FileReader;t.onload=()=>{e(pn(t))},t.onerror=t=>{kn.warn(`unable to decode data ${t}`),e("")},un(t,a)}))),t=i.type||"application/octet-stream";try{s=$t({dataUri:`data:${t};base64,${vo.encode(e)}`})}catch(e){ss.warn(`content: failed to get blob data from ${n}`,e)}}var a;t($t({t:$t({url:r,tfd:s}),c:o
}))}));return function(e){return n.apply(this,arguments)}}()),is=$t({setInterval:e=>{let t;e.onMessage.addListener((n=>{"setInterval"==n.method&&(t=eo(e.postMessage,n.t))})),e.onDisconnect.addListener((()=>{t&&no(t),t=null}))},registerMenuCommand:e=>{const t=es("registerMenuCommand");t?(t.onMessage.addListener((t=>{if("ack"in t)e.postMessage(t);else{const{method:n,event:o}=t;e.postMessage($t({method:n,event:o}))}})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{
const{messageId:n,name:o,uuid:s,accessKey:r,autoClose:i,title:c,id:a}=e,d=Jt([a,ts,s],"#");t.postMessage($t({messageId:n,method:"registerMenuCommand",name:o,title:c,uuid:s,menuId:d,accessKey:r,autoClose:i}))})),e.onDisconnect.addListener((()=>{t.disconnect()}))):to((()=>e.disconnect()),1)},notification:e=>{const t=es("notification");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),
e.onDisconnect.addListener((()=>{t.disconnect()}))):to((()=>e.disconnect()),1)},openInTab:e=>{const t=es("openInTab");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{const{messageId:n}=e;if("method"in e){const{method:o}=e;if("openInTab"==o)if("url"in e){let o=e.url;const{active:s,loadInBackground:r,insert:i,incognito:c,setParent:a}="boolean"==typeof e.options||void 0===e.options?$t({loadInBackground:e.options
}):e.options,d=void 0===s?void 0!==r&&!r:s,l=void 0===i||i;o&&"//"==mn(o,0,2)&&(o=lo.protocol+o),t.postMessage($t({messageId:n,method:"openInTab",details:$t({url:o,options:$t({active:!!d,insert:!!l,incognito:!!c,setParent:!c&&!!a})}),uuid:e.uuid}))}else t.postMessage(e);else ss.warn(`content: unknown method ${o}`)}else"name"in e?t.postMessage($t({messageId:n,name:e.name})):"focus"in e?t.postMessage($t({messageId:n,focus:!0})):"close"in e&&t.postMessage($t({messageId:n,close:!0}))})),
e.onDisconnect.addListener((()=>{t.disconnect()}))):to((()=>e.disconnect()),1)},download:e=>{let t;const n=es("download");if(!n)return void to((()=>e.disconnect()),1);let o;n.onMessage.addListener((t=>{e.postMessage(t)})),n.onDisconnect.addListener((()=>{e.disconnect(),t=!0})),e.onMessage.addListener((e=>{if("cancel"in e)t=!0,n.postMessage($t({cancel:!0,id:ts,uuid:e.uuid}));else if("details"in e){const{details:s,messageId:r,uuid:i}=e;rs(s).then((({t:e,c})=>{if(t)return void(c&&c());o=c
;const{url:a,...d}=s;n.postMessage($t({messageId:r,method:"download",details:$t({...d,from:e}),id:ts,uuid:i,location:lo.href}))}))}else n.postMessage($t({messageId:e.messageId,method:"download",uuid:e.uuid,id:e.id}))})),e.onDisconnect.addListener((()=>{o&&o(),o=void 0,n.disconnect()}))},webRequest:e=>{const t=es("webRequest");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{const{messageId:n,rules:o,uuid:s}=e
;t.postMessage($t({messageId:n,method:"webRequest",rules:o,uuid:s}))})),e.onDisconnect.addListener((()=>{t.disconnect()}))):to((()=>e.disconnect()),1)},xhr:e=>{let n,o;const s=[];let r;const i=function(){var e=t((function*(e){if(e&&Kt(s,e),o)yield o,i();else{const e=Wt(s);e&&e()}}));return function(t){return e.apply(this,arguments)}}(),c=es("xhr");c?(c.onMessage.addListener((n=>{"ack"in n?e.postMessage(n):i((()=>{const{onpartial:s,data:r,...i}=n;let c;if(s&&r){const{tfd:n}=r;if(n){
const r=(e=>e&&(Do(e)||xo(e)||Ro(e)||jo(e))?(e=>{let t,n,o,s,r;if(xo(e))t=e.objUrl.url;else if(Do(e))n=e.blob;else if(Ro(e))o=e.dataUri;else{if(!jo(e))throw"incompatible TransferableData";s=e.binary,r=e.type}return $t({toBlob:()=>Fn((e=>{if(n)e(n);else if(t)try{cn(ao(t),(t=>{cn(mo(t),(t=>{e(t)}))}))}catch(t){e(void 0)}else if(o)e(_o(o));else{if(void 0===s)throw"incompatible Transferable";{const t=bo(s);e(new Cn([t],r?$t({type:r}):void 0))}}})),dispose:()=>{t&&Sn(t),t=n=o=s=void 0}})
})(e):void 0)(n);if(!r)return;return void(o=Fn(function(){var n=t((function*(t){const n=()=>{o=null,t(),r&&r.dispose()};try{const t=yield r.toBlob();if(!t)return void n();const o=t.type;let a;if(a="arrayBuffer"in t?yield fo(t):yield go(new po(t)),!a)return void n();c=$t({nada:$t({buffer:a,type:o})}),e.postMessage($t({...i,onpartial:s,data:c})),n()}catch(e){ss.warn(e),n()}}));return function(e){return n.apply(this,arguments)}}()))}c=r}else c=r;e.postMessage($t({...i,onpartial:s,data:c}))}))})),
c.onDisconnect.addListener((()=>{i(function(){var o=t((function*(){e.disconnect(),n=!0}));return function(){return o.apply(this,arguments)}}())})),e.onMessage.addListener((e=>{Ho&&(e=((e,t=[])=>{const n=(e,o)=>{if(null===e)return null;if("object"==typeof e){const s=on(e);if(-1!=zt(t,s))return e;if(o){if(-1!==zt(o,e))throw"Converting circular structure to clone";At(o,o.length,e)}else o=[e];if(Dt(e)){const t=[];for(let s=0;s<e.length;s++){let r;r=Vt(e,s)?Tt(e,s):kt(e,s);const i=n(r,o);Kt(t,i)}
return o.length-=1,t}if("Object"===s){const t=$t({});return Yt(Mt(e),(s=>{const r=n(e[s],o);void 0!==r&&(t[s]=r)})),o.length-=1,t}throw`Unsupported type in clone: ${s}`}return e};return n(e)})(e,["Blob","File","ArrayBuffer"]));const{details:t}=e;(t?rs(t):Fn((e=>e()))).then((o=>{const{t:s,c:i}=o||$t({});if(n)return void(i&&i());let a,d;r=i,s&&t?(a=$t({...t,...s}),d=$t({...e,details:a,location:lo.href})):d=e,c.postMessage(d)}))})),e.onDisconnect.addListener((()=>{r&&r(),r=void 0,c.disconnect()
}))):to((()=>e.disconnect()),1)},onurlchange:e=>{const t=es("onurlchange");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):to((()=>e.disconnect()),1)},onaudiostatechange:e=>{const t=es("onaudiostatechange");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{
t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):to((()=>e.disconnect()),1)},values:e=>{const t=es("values");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):to((()=>e.disconnect()),1)},backgroundControl:e=>{const t=es("backgroundControl");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),
t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e)})),e.onDisconnect.addListener((()=>{t.disconnect()}))):to((()=>e.disconnect()),1)},keepAlive:e=>{const t=es("keepAlive");t?(t.onMessage.addListener((t=>{e.postMessage(t)})),t.onDisconnect.addListener((()=>{e.disconnect()})),e.onMessage.addListener((e=>{t.postMessage(e),Fo.lastError})),e.onDisconnect.addListener((()=>{t.disconnect()}))):to((()=>e.disconnect()),1)}}),cs=$t({
setTimeout:({args:e,cb:t})=>{to(t,e.t)},setClipboard:({args:e,cb:t})=>{const{content:n,info:o,uuid:s}=e;let r,i;"object"==typeof o?(o.type&&(r=o.type),o.mimetype&&(i=o.mimetype)):"string"==typeof o&&(r=o);const c=i||("html"==r?"text/html":"text/plain");bt.document.addEventListener("copy",(e=>{e.stopImmediatePropagation(),e.preventDefault(),e.clipboardData&&e.clipboardData.setData(c,n)}),$t({capture:!0,once:!0})),bt.document.execCommand("copy"),t()},closeTab:({args:{uuid:e},cb:t})=>{
Xo.sendMessage($t({method:"closeTab",uuid:e,id:ts}),(e=>{e&&e.error&&ss.warn(e.error),t(e)}))},focusTab:({args:{uuid:e},cb:t})=>{Xo.sendMessage($t({method:"focusTab",uuid:e,id:ts}),(e=>{e&&e.error&&ss.warn(e.error),t(e)}))},navigateTab:({args:{uuid:e,url:t},cb:n})=>{Xo.sendMessage($t({method:"navigateTab",uuid:e,url:t,id:ts}),(e=>{e&&e.error&&ss.warn(e.error),n(e)}))},addElement:(as=t((function*({args:e,node:t,cb:o}){try{const s=wo(e.tag,$t({...e.properties||$t({}),...e.id?$t({id:e.id}):$t({})
}));let r,i;if("script"===e.tag&&(r=Oo())&&s.setAttribute("nonce",r),t)i=t;else{const e=bt.document;if(i=e.head||e.body||e.documentElement,!i){const e=bt.document;i=yield Fn((t=>n((()=>t(e.head||e.body)))))}}i.appendChild(s),r&&s.removeAttribute("nonce"),o()}catch(e){ss.warn("content: error adding script",e)}})),function(){return as.apply(this,arguments)}),tabs:({args:e,cb:t})=>{e.method="tabs",Xo.sendMessage(e,(e=>e&&t(e.data)))},cookie:({args:e,cb:t})=>{e.method="cookie",
Xo.sendMessage(e,(e=>e&&t(e.data)))},audio:({args:e,cb:t})=>{e.method="audio",Xo.sendMessage(e,(e=>e&&t(e.data)))}});var as;const ds=$t({init:()=>{ts=twod.contextId},setup:(e,t)=>{ns=e,os=t},processMessage:({method:e,args:t,node:n},o)=>{let s;if(s=cs[e])return s($t({args:t,node:n,cb:o}));ss.warn(`content: unknown method ${e}`),o()},processConnect:(e,t)=>{let n;if(n=is[e])return n(t)}}),ls=["GM_info","GM.info"],us=["unsafeWindow","navigate",...ls],ps=e=>e.replace(new RegExp("[\"']","g"),"\\$1")
;let gs=!1;const ms=(e,n,o,s,r)=>{const{console:i}=twod;gs=gs||e.logLevel>=60;const{version:c,injectMode:a,inIncognitoContext:d,isFirstPartyIsolation:l,downloadMode:u,relaxedCsp:p,userAgent:g,container:m,logLevel:f}=e,h=$t({version:c,injectMode:a,inIncognitoContext:d,isFirstPartyIsolation:l,downloadMode:u,relaxedCsp:p,container:m});Yt(n,function(){var n=t((function*(t){const{script:n,storage:c}=t,{name:a,uuid:d,options:{run_at:l}}=n,{requires:u,...p}=n,m=u.length,v=!n.options.unwrap,b=$t({...h,
userAgent:g,logLevel:f,sandboxMode:r});let _,w;const y=((e,t)=>{const{measure_scripts:n,top_level_await:o,enforce_strict_mode:s}=e,{source_url:r,script:i,code:c}=t,{name:a,grant:d}=i,{requires:l}=i,u=!i.options.unwrap,p=l.map((e=>e.textContent||"")).join("\n");if(u){let e="";const t=["define","module","exports"],l=t.map((()=>"undefined")),u=-1!==i.grant.indexOf("none");let g;return g=u?ls:d.concat(us),g.forEach((e=>{const n=e.split(".")[0];"window"!==n&&-1===t.indexOf(n)&&(t.push(n),
l.push(`p.${n}`))
})),[`with (${u?"this.s":"this"}) {`,"(async (u, { p, r, s }) => {","try {",n?`console.time("${e=`SCRIPT RUN TIME[${ps(a)}]`}");\n`:"","r(u, s, [",l.join(","),"]);",n?`console.timeEnd("${e}");\n`:"","} catch (e) {","if (e.message && e.stack) {","console.error(\"ERROR: Execution of script '",ps(a),"' failed! \" + e.message);","console.log(e.stack);","} else {","console.error(e);","}","}","})","(",(o?"async ":"")+"function(",t.join(","),") {",s?'"use strict";\n':"\n",p,c,"\n",`}, ${u?"this":"seed"})`,"}","\n",r?`//# sourceURL=${r}\n`:""].join("")
}return[p,c,"\n",r?`//# sourceURL=${r}\n`:""].join("")})(e,t);return v?(_=()=>{gs&&i.debug(`env: inject "${a}" now`);const e=`__f__${Xn()}`,t=$t({storage:c,script:p}),n=`window["${e}"] = function(){${y}}`;let r=!0;s.once(`scriptack-${e}`,(()=>{gs&&!r&&i.log(`env: execution of "${a}" was delayed`),o(n,(e=>{e&&i.error(`Uncaught SyntaxError: ${e}`)}))})),s.send("script",$t({id:e,unwrap:!1,bundle:t,flags:b})),r=!1},w="context-menu"==l||"document-start"==l?void 0:()=>{
gs&&i.debug(`env: run "${a}" now  (${m} requires)`),s.send("run",$t({uuid:d}))}):w=()=>{gs&&i.debug(`env: inject @unwrap "${a}" now`),o(y,(e=>{e&&i.error(`Uncaught SyntaxError: ${e}`)}))},fs(a,l,_,w,gs)}));return function(e){return n.apply(this,arguments)}}())},fs=(e,t,o,s,r)=>{const{console:i}=twod;let c;"document-start"==t?(r&&i.debug(`env: run "${e}" ASAP -> document-start`),c=e=>e()):"document-body"==t?(r&&i.debug(`env: schedule "${e}" for document-body`),
c=yo):"context-menu"==t?r&&i.debug(`env: run "${e}" ASAP -> context-menu`):"document-end"==t?(r&&i.debug(`env: schedule "${e}" for document-end`),c=e=>n(!1,e)):(r&&i.debug(`env: schedule "${e}" for document-idle`),c=Mo),o&&o(),s&&c&&c((()=>{s()}))},hs=(e,t)=>{let n,o;try{o=(0,eval)(e)}catch(e){n=e.message||e}return t&&t(n),o},vs=({sendPrefix:e,listenPrefix:n,cloneInto:o})=>{const s=e=>o?o(e,bt.document):e,i=$t({});let c,a,d=1;const l=$t({});let u=!1,p=[];const g=()=>{
_=bt.document.documentElement,u=!1;const e=p;p=[],Yt(e,(e=>{u||y()?Kt(p,e):e()}))};let m;const f=e=>{const t=++d;return l[d]=e,t},h=(e,t)=>{const{m:n,a:o,r,n:i}=t,{m:c,c:a}=((e,t,n)=>{let o,r;return n?(r=new Rn(e,$t({relatedTarget:n})),o=new Dn(e,$t({detail:s(t)}))):o=new Dn(e,$t({detail:s(t)})),$t({m:r,c:o})})(e,$t({m:n,a:o,r}),i);c&&Ct(Ge,bt,[c]),Ct(Ge,bt,[a])},v=t=>{const n=(e=>{if("MouseEvent"===on(e)){const t=yn(e);if(!t)throw"Invalid MouseEvent";return void(m=t)}const t=nn(Mn(e))
;return m&&(t.n=m,m=void 0),t})(t);if(!n)return;const{m:o,r:s,a:r,n:d}=n;if(i[o]&&(Yt(i[o],(e=>e(r))),delete i[o]),"unlock"==o)h(`${e}_${a}`,$t({m:"unlocked",a:void 0,r:null})),g();else if("unlocked"==o)g();else if("message.response"==o){if(null==s)throw"Invalid Message";((e,t)=>{let n;e&&(n=l[e])&&(n(t),delete l[e])})(s,r)}else if(c){const t=s?t=>{h(`${e}_${a}`,$t({m:"message.response",a:t,r:s}))}:()=>{};c($t({method:o,args:r,node:d}),t)}},b=e=>{e&&(a=e),a&&Bn.addEventListener(`${n}_${a}`,v,!0)
};let _,w;const y=()=>{if((()=>{const e=bt.document.documentElement;return _||(_=e),_!==e})()){if(w){const e=w;w=void 0,e(bt.document)}return!0}},M=e=>(_=bt.document.documentElement,Fn(function(){var n=t((function*(t){if(w=t,r&&!e&&(yield null,y()))return;const n=new Pn((()=>{y()&&n.disconnect()}));n.observe(bt.document,$t({childList:!0}))}));return function(e){return n.apply(this,arguments)}}())),L=$t({init:(E=t((function*(t,n){a?b():b(t),M(n).then((()=>{u=!0,L.refresh(),h(`${e}_${a}`,$t({
m:"unlock",a:void 0,r:null}))}))})),function(e,t){return E.apply(this,arguments)}),refresh:()=>{const e=a;e&&(L.cleanup(),L.init(e,!0))},switchId:e=>{a&&L.cleanup(),b(e)},send:(t,n,o,s)=>Fn((r=>{let i,c;"function"!=typeof o&&null!==o?(i=o,c=s):c=o,y();const d=()=>{h(`${e}_${a}`,$t({m:t,a:n,r:c?f(c):null,n:i})),r()};u?Kt(p,d):d()})),sendToId:(t,n,o)=>{h(`${e}_${t}`,$t({m:n,a:o,r:null}))},setMessageListener:e=>{c=e},once:(e,t)=>{i[e]||(i[e]=[]),Kt(i[e],t)},cleanup:()=>{
a&&(Bn.removeEventListener(`${n}_${a}`,v,!0),a=void 0)}});var E;return L},bs=function(e,t,n,o,s){let r;const i=Oo(),c=wo("script");i&&c.setAttribute("nonce",i);try{c.textContent=t,e.appendChild(c)}catch(e){r=e.message||e}if(i&&c.removeAttribute("nonce"),!s){const e=c.parentNode;e&&e.removeChild(c)}return o&&o(r),!r},_s=(e,t)=>{try{bs(uo.head||uo.body||uo.documentElement||uo,e,0,t)}catch(e){t&&t(e.message||e)}};let ws,ys;const Ms=e=>{const t=es("tabInfo");t?(t.onMessage.addListener((e=>{
if("ack"in e);else{const{info:t}=e;t?ws=nn(t):Qn.warn("tabInfo: unexpected message",e)}})),t.onDisconnect.addListener((()=>{Ls()})),e(t)):to((()=>Ms(e)),100)},Ls=()=>{Ms((e=>{ws=ys||ws,ys=void 0,e.postMessage($t({method:"tabInfo",messageId:Xn(),info:ws}))}))},Es=e=>{e=e||Bn.location.href;const t=es("tabInfo");t?(t.onMessage.addListener((e=>{"ack"in e||Qn.warn("tabInfo.frame: unexpected message",e)})),t.onDisconnect.addListener((()=>{Es(e)})),t.postMessage($t({method:"tabInfo",messageId:Xn(),
url:e}))):to((()=>Es(e)),100)};let Is=!1;const Ss=location.pathname+location.search;Fo.short_id,window.btoa(Ss.length+Ss).substr(0,255).replace(/[#=/]/g,"_");let Os=!1;const xs=(e,t,o)=>{const{contextId:s,bridges:r,console:i}=twod;let c;Fn((n=>{const o=e=>{let t=1;const o=()=>{Is&&i.log('content: send "prepare" message'),Xo.sendMessage({method:"prepare",id:s,topframe:oo,url:window.location.href},(s=>{if(!Os){if(!s)return Is&&i.log("content: _early_ execution, connection to bg failed -> retry!"),
window.setTimeout(o,t),void(t=Pt(2*t,3e3));Os=!0,s.nonce&&So(s.nonce),Mt(s.contexters).length||Mt(s.scripts).length||s.external_connect?(e&&e(s),n({info:s,type:"complete"==bn(bt.document)?"late":"normal"})):n({info:s})}}))};!function(e){const t=()=>"prerender"!==document.webkitVisibilityState,n=()=>{t()&&(document.removeEventListener("webkitvisibilitychange",n,!1),e())};t()?e():document.addEventListener("webkitvisibilitychange",n,!1)}(o)},r=()=>{let r
;if(Is&&i.log("content: Started ("+s+", "+window.location.origin+window.location.pathname+")",_t.tm_info),r=_t.tm_info){delete _t.tm_info,r.nonce&&So(r.nonce);const{contexters:o,scripts:i}=r;if(Mt(o).length||Mt(i).length){if(r.contexters.raw||r.scripts.raw)if(e.raw)void 0===c&&(c=e.raw());else if(!t)throw"raw inject missing";n({info:r,type:"sync"})}else n({info:r});{let e;if("userscripts-dynamic"===r.contentMode){const t=e={};Yt(Mt(i),(e=>{const n=i[e]
;n&&Yt(n,(({script:{uuid:e,name:n}})=>t[e]=n))}))}Xo.sendMessage({method:"prepare",id:s,topframe:oo,url:window.location.href,scripts:e,cleanup:!0},(()=>null))}}else t?o((({scripts:t,contexters:n})=>{e.raw&&void 0===c&&(t.raw||n.raw)&&(c=e.raw())})):(e.raw&&void 0===c&&(c=e.raw()),o())};t?window.setTimeout((()=>r()),1):r()})).then((({info:a,type:d})=>{const{external_connect:l}=a;if(!t&&(e=>{if(e){const t=location.href.split("#")[0];return e.some((({source:e,flags:n})=>{const o=new $n(e,n)
;if(""===t.replace(o,""))return!0}))}return!1})(l)&&(void 0===c&&e.raw&&(c=e.raw()),c||i.warn("content: external connectability detected, but unable to initialize raw mode!"),Nn((()=>r.first.send("external.connect")))),d){Is=Is||a.logLevel>=60;const{scripts:c,sharedBlobs:l,sharedObjectUrls:p}=a;if(ds.setup(l,p),c.raw){let n;t&&!e.raw&&(n=!0),n&&(e.js?(c.js=(c.js||[]).concat(c.raw||[]),delete c.raw):e.dom&&(c.dom=(c.dom||[]).concat(c.raw||[]),delete c.raw))}if(c.js){
if(!e.js)throw"js inject missing";e.js()}if(c.dom){if(!e.dom)throw"dom inject missing";e.dom()}n(!1,(()=>{Is&&i.log("content: DOMContentLoaded"),Yt(Mt(r),(e=>r[e].send("DOMContentLoaded")))})),u=()=>{Is&&i.log("content: load"),Yt(Mt(r),(e=>r[e].send("load")))},"complete"==bn(bt.document)?u():Bn.addEventListener("load",(()=>u()),$t({capture:!0,once:!0}));const g=(c.dom||[]).length+(c.js||[]).length+(c.raw||[]).length
;Is&&i.log("content: "+(d||"normal")+" start event processing for "+s+" ("+g+" to run)"),Ds(a,"sync"===d),!oo&&g&&Es(location.href),o()}else o();var u}))},Ds=e=>{const{bridges:t}=twod,{scripts:n,...s}=e;n.js&&ms(s,n.js,Jo,t.js,"js"),n.dom&&(Yt(o,(e=>_t[e]=void 0)),ms(s,n.dom,hs,t.dom,"dom")),n.raw&&ms(s,n.raw,_s,t.raw,"raw")},Rs=function(){var e=t((function*(){const{contextId:e}=twod,{location:t,document:n}=bt;n.addEventListener("mouseenter",(()=>{try{Xo.sendMessage($t({method:"contextmenu",
url:t.href,id:e}),(()=>{}))}catch(e){}}),!1)}));return function(){return e.apply(this,arguments)}}();let js;t((function*(){const{unsafeWindow:e,bridges:t}=twod,{location:n,document:o}=e,r=o instanceof XMLDocument;if(!$t({"http:":!0,"https:":!0,"file:":!0})[e.location.protocol])return;oo&&(Ls(),Bn.addEventListener("pagehide",(e=>{Ln(e)&&(ys=ws)})));const i=twod.contextId?twod.contextId:twod.contextId=Xn();let c;const a=$t({});Et(twod.console,Qn),Fn((n=>{if(Ho){const{createBridge:e}=Vo(i)
;o=(o,s)=>{js=c=o;const{modes:i}=s;i.js&&(t.js=e(),a.js=()=>!1,r&&(i.raw=!1)),n(s)},Kt(Yo,o)}else Fn((t=>{js=c=e.pagejs,delete e.pagejs,js?t():(()=>{let e=n=>{delete bt.pagejs,e=void 0,(e=>{if(!e)throw"Error: pagejs missing. Please see http://tmnk.net/faq#Q208 for more information.";js=c=e,t()})(n)};It(bt,"pagejs",$t({set:e,configurable:!0})),to((()=>{e&&e()}),1)})()})).then((()=>{n($t({modes:$t({js:!1,raw:!0,dom:!0})}))}));var o})).then((({modes:{dom:o,raw:d},answer:l})=>{var u
;if(l&&(u=l).scripts&&u.contexters&&(_t.tm_info=l),o){const e=Ho?hs(`() => ${c};`)():c,{createBridge:n,inject:o}=((e,t)=>{const n=(e,t)=>{Yt(s,(n=>n(e,t)))},o=e=>Kt(r,$t({listener:e,clone:e=>e})),s=[],r=[],i=(e,t)=>{Yt(r,(({listener:n,clone:o})=>n(e,o(t))))},c=e=>Kt(s,e),a="c"+Xn();let d;return $t({createBridge:()=>(d=qo($t({sendPrefix:"2S",listenPrefix:"2U",send:i,onMessage:c})),d.init(e),d),inject:()=>(t($t({unsafeWindow:bt,unsafeThis:_t,pageWindow:void 0,contextId:a,fSend:n,fOnMessage:o})),
d.sendToId(a,"commid",$t({id:e})),!0)})})(i,e);a.dom=o,t.dom=n()}if(d){const{createBridge:e,inject:n}=((e,t)=>{let n;return $t({createBridge:()=>(n=vs($t({sendPrefix:"2P",listenPrefix:"2C",cloneInto:ho})),n),inject:()=>{n.init(e);let o=!1;const r=Xn(),i="("+sn(((e,t)=>{const n=window,o=t(n),s=n.parent,{O_dPy:r,cSO:i}=o;r(s,e,i({value:o,enumerable:!1,writable:!1,configurable:!0}))}))+')("'+r+'", '+sn(s)+")";return n.once("ack",(()=>{o=!0})),(o=>{((e,t)=>{
const n=An(wn(bt.document,"*"),0)||bt.document,o=wo("div"),s=o.attachShadow($t({mode:"closed"}));s.appendChild(wo("style",":host { display: none }"));const r=wo("iframe",$t({sandbox:"allow-scripts allow-same-origin",style:"display: none",src:"javascript:void 0"}));let i=()=>{if(null===i)return;i=null;let n=!1;try{const t=r.contentDocument,o=r.contentWindow;t&&o&&(n=bs(An(t.getElementsByTagName("*"),0),e))}catch(e){}t(o,n),r.remove(),o.remove()};r.addEventListener("load",i,$t({once:!0,capture:!0
})),s.appendChild(r),n.appendChild(o),i&&i()})(o,((o,s)=>{bs(o,`(${t})({ unsafeWindow: typeof globalThis === "undefined" ? window : globalThis, unsafeThis: window, vault: ${s?`window["${r}"]`:"null"}, contextId: "${r}", __proto__: null });delete window["${r}"]\n`,0,(()=>{n.sendToId(r,"commid",$t({id:e}))}),!0)}))})(i),o}})})(i,c);a.raw=n,t.raw=e()}const p=t.first=t.js||t.raw||t.dom;Xo.onMessage.addListener(((t,o,s)=>{
"executeScript"==t.method?(t.url&&0!==fn(n.href,t.url)||void 0!==t.topframe&&t.topframe!=oo||Ds(t.info,!1),s($t({}))):oo&&("loadUrl"==t.method?(e.location=t.url,s($t({}))):"reload"==t.method?(n.reload(),s($t({}))):"setForeignAttr"==t.method?(p.send(t.method,t),s($t({}))):Qn.log("content: unknown method "+(e=>{const t=(e,n)=>{let o;if(null===e)o="null";else{const s=typeof e;if("object"===s){if(n){if(-1!=zt(n,e))throw"Converting circular structure to JSON";At(n,n.length,e)}else n=[e];if(Dt(e)){
let s="";for(let o=0;o<e.length;o++){let r;r=Vt(e,o)?Tt(e,o):kt(e,o);const i=t(r,n);s+=`${o?",":""}${void 0===i?"null":i}`}o=`[${s}]`}else{let s="";Yt(Mt(e),(o=>{const r=t(e[o],n);void 0!==r&&(s+=`${s?",":""}${R(o)}: ${r}`)})),o=`{${s}}`}n.length-=1}else{if("bigint"===s)throw"Do not know how to serialize a BigInt";o=R(e)}}return o};return t(e)})(t)))})),qn.onConnect.addListener(((e,t)=>{ds.processConnect(e,t)})),ds.init(),Yt(Mt(t),(e=>{if("first"==e)return;const n=t[e]
;n.setMessageListener(((t,o)=>{const{method:s,args:r}=t;if("port.message"==s)qn.message(r,n);else if("csp"==s){let t;t="raw"==e?_s:"dom"==e?hs:Jo,t(r.src,(e=>{e&&Qn.error(`Uncaught Error: ${e}`)}))}else if("external.message"==s)Xo.sendMessage($t({method:"externalMessage",request:r}),(e=>{o(e)}));else if("console"==s){const e=r,t=An(e,0),n=An(e,1),o=Qn[t]||Qn.log;o&&Ct(o,Qn,((e,...t)=>{let n=e.length;const o=$t(e);for(let e=0;e<t.length;e++){const s=t[e],r=Dt(s)?s:[s]
;for(let e=0;e<r.length;e++)o[n+e]=Ut(r,e);n+=r.length}return Lt(o)})(["injected:"],(e=>{const t=[];return Yt(e,(e=>{Kt(t,(e=>"string"==typeof e?Nt(e):e)(e))})),t})(n)))}else"commid"==s||(e=>"ack"==e.method||"injectableack"==e.method||0===fn(e.method,"scriptack-"))(t)||ds.processMessage(t,o)}))})),xs(a,r,(()=>js=void 0)),Rs()}))}))()})();})({ __proto__: null, unsafeWindow: typeof globalThis === "undefined" ? window : globalThis, unsafeThis: window, }, "tm_fqr0tk")