this.pagejs=e=>{(()=>{"use strict";function t(e,t,n,o,r,s,i){try{var a=s(e,i),l=$t(a,"value")}catch(e){return void n(e)}$t(a,"done")?t(l):dn(new gn((e=>e(l))),o,r)}function n(e){const n=function(){var n=this,o=arguments;return new gn((function(r,s){function i(e){t(l,r,s,i,a,pn,e)}function a(e){t(l,r,s,i,a,fn,e)}var l=Pt(e,n,o);i(void 0)}))};return Dt(n,"apply",(function(e,t){return Pt(n,e,t)})),n}const o=["chrome"],r="vault"in e;if(r&&void 0===e.vault)throw"Invalid vault"
;const s=e.vault=e.vault||(e=>{const t=Object.call,n=t.bind(t),o=Object.assign,r=Object.getOwnPropertyDescriptor,s=Object.getPrototypeOf,i=e=>o({__proto__:null},e),a=s(function*(){}()),l=s(Uint8Array.prototype);return i({sourceWindow:e,cSO:i,F_c:n,F_a:Object.apply,F_b:Object.bind,F_tS:Function.toString,A_fE:[].forEach,A_so:[].some,A_sh:[].shift,A_j:[].join,A_iO:[].indexOf,A_iA:Array.isArray,O_a:o,O_k:Object.keys,O_v:Object.values,O_dP:Object.defineProperties,O_dPy:Object.defineProperty,
O_hOP:Object.hasOwnProperty,O_gOPN:Object.getOwnPropertyNames,O_gOPD:r,O_gOPDs:Object.getOwnPropertyDescriptors,O_gPO:s,O_tS:{}.toString,J_p:JSON.parse,J_s:JSON.stringify,M_f:Math.floor,M_r:Math.random,M_m:Math.max,M_mi:Math.min,N_tS:(0).toString,N_MSI:Number.MAX_SAFE_INTEGER,P_t:Promise.prototype.then,P_c:Promise.prototype.catch,P_co:Promise.prototype.constructor,G_n:a.next,G_t:a.throw,R_rABS:FileReader.prototype.readAsBinaryString,R_rAT:FileReader.prototype.readAsText,
R_r:r(FileReader.prototype,"result").get,R_enq:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.enqueue:null,R_cl:e.ReadableStreamDefaultController?e.ReadableStreamDefaultController.prototype.close:null,S_fCC:String.fromCharCode,S_sl:"".slice,S_su:"".substr,S_sp_nr:"".split,S_iO:"".indexOf,S_tr:"".trim,S_r_nr:"".replace,S_rA_nr:"".replaceAll,S_cCA:"".charCodeAt,S_tLC:"".toLowerCase,S_tUC:"".toUpperCase,Y_tST:Symbol.toStringTag,Y_unsc:Symbol.unscopables,
USP_tS:URLSearchParams.prototype.toString,D_pFS:DOMParser.prototype.parseFromString,U_cOU:URL.createObjectURL,U_rOU:URL.revokeObjectURL,X_o:XMLHttpRequest.prototype.open,X_pSD:XMLHttpRequest.prototype.DONE,X_pSH:XMLHttpRequest.prototype.HEADERS_RECEIVED,X_pSL:XMLHttpRequest.prototype.LOADING,X_pSO:XMLHttpRequest.prototype.OPENED,X_pSU:XMLHttpRequest.prototype.UNSENT,X_s:XMLHttpRequest.prototype.send,D_n:Date.now,I_tS:e=>""+e,E_r:Element.prototype.remove,E_s:Element.prototype.setAttribute,
E_rA:Element.prototype.removeAttribute,D_cS:r(Document.prototype,"currentScript").get,D_gRS:r(Document.prototype,"readyState").get,D_cE:Document.prototype.createElementNS,D_gEBT:Document.prototype.getElementsByTagName,M_rT:r(MouseEvent.prototype,"relatedTarget").get,C_d:r(CustomEvent.prototype,"detail").get,P_p:r(PageTransitionEvent.prototype,"persisted").get,C_pA:CustomEvent.prototype.AT_TARGET,M_d:MutationObserver.prototype.disconnect,W_aEL:addEventListener,W_rEL:removeEventListener,
TA_b:r(l,"buffer").get,TA_sa:Uint8Array.prototype.subarray,parseInt,parseFloat,CustomEvent,CompositionEvent,KeyboardEvent,MouseEvent,MutationObserver,console:Object.assign({},console),Error,Uint8Array,Blob,ReadableStream,Number,String,Proxy,Window,FileReader,DOMParser,XMLHttpRequest,Function,RegExp,Promise,encodeURIComponent,decodeURIComponent,encodeURI,decodeURI,escape,unescape,atob,btoa,setTimeout,clearTimeout,setInterval,clearInterval,postMessage,dispatchEvent,alert,prompt,confirm,close,
getElementById:e.Document.prototype.getElementById,createEvent:e.Document.prototype.createEvent,createElement:e.Document.prototype.createElement})
})(e.unsafeWindow),{cSO:i,F_c:a,F_a:l,F_b:c,F_tS:u,A_fE:d,A_so:g,A_sh:p,A_j:f,A_iO:v,A_iA:m,O_a:_,O_k:h,O_v:b,O_dP:M,O_dPy:y,O_hOP:w,O_gOPN:E,O_gOPD:S,O_gOPDs:G,O_gPO:L,O_tS:R,J_p:I,J_s:O,M_f:C,M_r:x,M_m:k,M_mi:T,N_tS:P,N_MSI:A,P_t:D,P_c:U,P_co:$,G_n:j,G_t:V,R_rABS:F,R_rAT:N,R_r:q,R_enq:B,R_cl:X,S_fCC:H,S_sl:W,S_su:K,S_iO:J,S_sp_nr:z,S_tr:Y,S_rA_nr:Q,S_cCA:Z,S_tLC:ee,S_tUC:te,Y_tST:ne,Y_unsc:oe,D_pFS:re,D_cS:se,D_gRS:ie,D_cE:ae,D_gEBT:le,E_r:ce,E_s:ue,E_rA:de,C_pA:ge,M_d:pe,C_d:fe,P_p:ve,M_rT:me,U_cOU:_e,U_rOU:he,USP_tS:be,X_o:Me,X_s:ye,X_pSD:we,X_pSH:Ee,X_pSL:Se,X_pSO:Ge,X_pSU:Le,D_n:Re,I_tS:Ie,W_aEL:Oe,W_rEL:Ce,TA_b:xe,TA_sa:ke,parseInt:Te,parseFloat:Pe,console:Ae,encodeURIComponent:De,decodeURIComponent:Ue,encodeURI:$e,decodeURI:je,escape:Ve,unescape:Fe,atob:Ne,btoa:qe,postMessage:Be,dispatchEvent:Xe,alert:He,prompt:We,confirm:Ke,close:Je,getElementById:ze,createEvent:Ye,createElement:Qe,CustomEvent:Ze,CompositionEvent:et,KeyboardEvent:tt,MouseEvent:nt,MutationObserver:ot,Uint8Array:rt,FileReader:st,DOMParser:it,XMLHttpRequest:at,Function:lt,RegExp:ct,Blob:ut,ReadableStream:dt,Number:gt,String:pt,Proxy:ft,Window:vt}=s,mt=e,{unsafeWindow:_t,unsafeThis:ht}=mt,bt=a,Mt=l,yt=h,wt=b,Et=_,St=M,Gt=y,Lt=E,Rt=S,It=L,Ot=G||(e=>{
const t=At({});for(const n in e)t[n]=Rt(e,n);return t}),Ct=m,xt=C,kt=x,Tt=k,Pt=(e,t,n)=>bt(Mt,e,t,n),At=i,Dt=(e,t,n)=>(Gt(e,t,At({value:n,configurable:!0,enumerable:!0,writable:!0})),e),Ut=(e,t)=>tn(e,t)?e[t]:void 0,$t=(e,t)=>{const n=Rt(e,t);return n?At(n).value:void 0},jt=(e,t)=>{const n=(e,t,o)=>{const r=Rt(e,t),s=r?At(r):void 0;let i;return s?s.enumerable?s.value:void 0:--o>=0&&(i=It(e))?n(i,t,o):void 0};return n(e,t,5)},Vt=e=>{const t=(t,...n)=>Pt(e,t,n);return Dt(t,"wrappedJSObject",e),t
},Ft=()=>e=>Vt(e),Nt=Vt(c),qt=e=>{const t=(e,n)=>{let o;if(null===e)o="null";else{const r=typeof e;if("object"===r){if(n){if(-1!=Zt(n,e))throw"Converting circular structure to JSON";Dt(n,n.length,e)}else n=[e];if(Ct(e)){let r="";for(let o=0;o<e.length;o++){let s;s=tn(e,o)?Ut(e,o):jt(e,o);const i=t(s,n);r+=`${o?",":""}${void 0===i?"null":i}`}o=`[${r}]`}else{let r="";en(yt(e),(o=>{const s=t(e[o],n);void 0!==s&&(r+=`${r?",":""}${O(o)}: ${s}`)})),o=`{${r}}`}n.length-=1}else{
if("bigint"===r)throw"Do not know how to serialize a BigInt";o=O(e)}}return o};return t(e)},Bt=e=>{const t=I(e),n=e=>{const t=[];for(let n=0;n<e.length;n++)Dt(t,n,o(e[n]));return t},o=e=>{if(null===e);else if("object"==typeof e){if(Ct(e))return n(e);{const t={};return en(yt(e),(r=>{const s=e[r];let i;i="object"==typeof s?Ct(s)?n(s):o(s):s,Dt(t,r,i)})),t}}return e};return o(t)},Xt=Ft()(g),Ht=(e,t,n,...o)=>{const r=o||[],s=Jt(e,0,t),i=Jt(e,t,n),a=Jt(e,t+n);let l=Yt([],s);return l=Yt(l,r),
l=Yt(l,a),At({result:l,removed:i})},Wt=Ft()(p),Kt=(e,t)=>{const n=[];return en(e,(e=>{t(e)&&Qt(n,e)})),n},Jt=(e,t,n)=>{const o=e.length;let r=t||0;if(r>=o)return[];r<0&&(r=Tt(0,o+r));let s=void 0===n?o:n;s<0&&(s=Tt(0,o+s)),s>o&&(s=o);const i=At({});for(let t=r;t<s;t++)i[t]=$t(e,t);return wt(i)},zt=Ft()(f),Yt=(e,...t)=>{let n=e.length;const o=At(e);for(let e=0;e<t.length;e++){const r=t[e],s=Ct(r)?r:[r];for(let e=0;e<s.length;e++)o[n+e]=$t(s,e);n+=s.length}return wt(o)},Qt=(e,t)=>{
let n=e.length||0;return Dt(e,n,t),n++,e.length=n},Zt=Ft()(v),en=Ft()(d),tn=Ft()(w),nn=Ft()(z),on=Ft()(W),rn=Vt(R),sn=It({}),an=e=>{const t=At(e),n=Lt(t);for(let e=0;e<n.length;e++){const o=n[e],r=t[o];null!==r&&"object"==typeof r&&It(r)===sn&&(t[o]=an(r))}return t},ln=e=>{const t=nn(rn(e)," ");return on(zt(Jt(t,1)," "),0,-1)},cn=(Ft()(u),Ft()(P)),un=A,dn=Ft()(D),gn=(Ft()(U),
Nt($,It((async()=>{})()))),pn=Ft()(j),fn=Ft()(V),vn=Ft()(F),mn=Ft()(N),_n=Ft()(q),hn=B?Ft()(B):B,bn=X?Ft()(X):X,Mn=H,yn=Ft()(K),wn=Ft()(J),En=Ft()(Y),Sn=(Ft()(Q||function(e,t){return zt(nn(this,e),t)}),Ft()(Z)),Gn=Ft()(ee),Ln=Ft()(te),Rn=ne,In=oe,On=Vt(re),Cn=Vt(se),xn=Vt(ie),kn=(Vt(ae),Vt(le),Vt(ce)),Tn=Vt(ue),Pn=Vt(de),An=ge,Dn=Vt(me),Un=Vt(fe),$n=(Vt(ve),pe&&Ft()(pe),Vt(be)),jn=Vt(xe),Vn=Ft()(ke),Fn=(Ft()(Me),we),Nn=Ee,qn=Se,Bn=Ge,Xn=Le,Hn=(Ft()(ye),
Re),Wn=ft,Kn=gt,Jn=Ze,zn=tt,Yn=nt,Qn=rt,Zn=ot,eo=ut,to=function(e,t){return $t(e,t)},no=At({addEventListener:!1,Array:!0,Blob:!0,close:!1,CustomEvent:!0,Date:!0,DOMParser:!0,Error:!0,Event:!0,FileReader:!0,KeyboardEvent:!0,location:!0,Math:!0,MouseEvent:!0,Number:!0,Object:!0,ReadableStream:!0,removeEventListener:!1,Uint8Array:!0,XMLHttpRequest:!0}),oo=(()=>{const e=At({getElementById:ze,createEvent:Ye,createElement:Qe,dispatchEvent:Xe,addEventListener,removeEventListener}),t=At({})
;return en(yt(e),(n=>{try{const o=e[n];t[n]=function(...e){return Pt(o,_t.document,e)}}catch(e){t[n]=((e,t)=>{if(so.error(`Tampermonkey sandbox preparation ${t?"("+t+") ":""}failed. This usually is caused by a third-party extension.`,e),t)return()=>{}})(e,`document.${n}`)}})),t})(),ro=At({top:!0,location:!0});e.bridges=e.bridges||At({});const so=e.console=e.console||At({}),io=At({addEventListener:Nt(Oe,_t),removeEventListener:Nt(Ce,_t)});en(yt(ro),(async e=>{if(!io[e])try{const t=_t[e]
;if(null==t)return;io[e]=t}catch(e){}})),en(yt(no),(async e=>{if(!io[e])try{let t=$t(_t,e);if(void 0===t&&(ht===_t||void 0===(t=$t(ht,e))))return;const n=no[e];io[e]=!1===n&&"function"==typeof t?Nt(t,ht):t}catch(e){}}));const ao=e=>{let t,n=[],o=!1;e((e=>{if(!o){if(n.length){const t=n;n=[],en(t,(t=>t(e)))}else t=e;o=!0}}));const r=At({then:e=>(o?e(t):Qt(n,e),r)});return r},lo=({sendPrefix:e,listenPrefix:t,send:o,onMessage:r})=>{if(void 0===o||void 0===r)throw"invalid args";let s,i,a=1
;const l=At({}),c=At({}),u=e=>{e&&(s=e)},d=e=>{const t=++a;return c[a]=e,t};r(((n,r)=>n==`${t}_${s}`?(t=>{const{m:n,r,a,n:u}=t;if(l[n]&&(en(l[n],(e=>e(a))),delete l[n]),"message.response"==n){if(null==r)throw"Invalid Message";((e,t)=>{let n;e&&(n=c[e])&&(n(t),delete c[e])})(r,a)}else if(i){const t=r?t=>{o(`${e}_${s}`,At({m:"message.response",a:t,r}))}:()=>{};i(At({method:n,args:a,node:u}),t)}})(r):null));const g=At({init:(p=n((function*(e){s?u():u(e)})),function(e){return p.apply(this,arguments)
}),refresh:()=>null,switchId:e=>{s&&g.cleanup(),u(e)},send:(t,n,r,i)=>ao((a=>{let l,c;"function"!=typeof r&&null!==r?(l=r,c=i):c=r,o(`${e}_${s}`,At({m:t,a:n,r:c?d(c):null,n:l})),a()})),sendToId:(t,n,r)=>{o(`${e}_${t}`,At({m:n,a:r,r:null}))},once:(e,t)=>{l[e]||(l[e]=[]),Qt(l[e],t)},setMessageListener:e=>{i=e},cleanup:()=>null});var p;return g},co=({sendPrefix:e,listenPrefix:t,cloneInto:o})=>{const s=e=>o?o(e,_t.document):e,i=At({});let a,l,c=1;const u=At({});let d=!1,g=[];const p=()=>{
b=_t.document.documentElement,d=!1;const e=g;g=[],en(e,(e=>{d||y()?Qt(g,e):e()}))};let f;const v=e=>{const t=++c;return u[c]=e,t},m=(e,t)=>{const{m:n,a:o,r,n:i}=t,{m:a,c:l}=((e,t,n)=>{let o,r;return n?(r=new Yn(e,At({relatedTarget:n})),o=new Jn(e,At({detail:s(t)}))):o=new Jn(e,At({detail:s(t)})),At({m:r,c:o})})(e,At({m:n,a:o,r}),i);a&&Pt(Xe,_t,[a]),Pt(Xe,_t,[l])},_=t=>{const n=(e=>{if("MouseEvent"===ln(e)){const t=Dn(e);if(!t)throw"Invalid MouseEvent";return void(f=t)}const t=an(Un(e))
;return f&&(t.n=f,f=void 0),t})(t);if(!n)return;const{m:o,r,a:s,n:c}=n;if(i[o]&&(en(i[o],(e=>e(s))),delete i[o]),"unlock"==o)m(`${e}_${l}`,At({m:"unlocked",a:void 0,r:null})),p();else if("unlocked"==o)p();else if("message.response"==o){if(null==r)throw"Invalid Message";((e,t)=>{let n;e&&(n=u[e])&&(n(t),delete u[e])})(r,s)}else if(a){const t=r?t=>{m(`${e}_${l}`,At({m:"message.response",a:t,r}))}:()=>{};a(At({method:o,args:s,node:c}),t)}},h=e=>{e&&(l=e),l&&io.addEventListener(`${t}_${l}`,_,!0)}
;let b,M;const y=()=>{if((()=>{const e=_t.document.documentElement;return b||(b=e),b!==e})()){if(M){const e=M;M=void 0,e(_t.document)}return!0}},w=e=>(b=_t.document.documentElement,ao(function(){var t=n((function*(t){if(M=t,r&&!e&&(yield null,y()))return;const n=new Zn((()=>{y()&&n.disconnect()}));n.observe(_t.document,At({childList:!0}))}));return function(e){return t.apply(this,arguments)}}())),E=At({init:(S=n((function*(t,n){l?h():h(t),w(n).then((()=>{d=!0,E.refresh(),m(`${e}_${l}`,At({
m:"unlock",a:void 0,r:null}))}))})),function(e,t){return S.apply(this,arguments)}),refresh:()=>{const e=l;e&&(E.cleanup(),E.init(e,!0))},switchId:e=>{l&&E.cleanup(),h(e)},send:(t,n,o,r)=>ao((s=>{let i,a;"function"!=typeof o&&null!==o?(i=o,a=r):a=o,y();const c=()=>{m(`${e}_${l}`,At({m:t,a:n,r:a?v(a):null,n:i})),s()};d?Qt(g,c):c()})),sendToId:(t,n,o)=>{m(`${e}_${t}`,At({m:n,a:o,r:null}))},setMessageListener:e=>{a=e},once:(e,t)=>{i[e]||(i[e]=[]),Qt(i[e],t)},cleanup:()=>{
l&&(io.removeEventListener(`${t}_${l}`,_,!0),l=void 0)}});var S;return E},uo=()=>cn(Hn()+19831206*kt()+1,36),go=function(){var e=n((function*(e){yield null,e()}));return function(t){return e.apply(this,arguments)}}(),po=()=>{const e=Cn(_t.document);e&&(Pn(e,"nonce"),kn(e))},fo=(()=>{const{console:t,bridges:n}=e,o=At({});let r;const s=(e,n,r,s)=>{let a,l=[],c=[],u=[],d=[];const g=()=>{c=[],u=[],d=[],m(),y=null,delete o[n]},p=t=>{e.send("port.message",At({response_id:n,value:t}))},f=e=>{
s&&"messageId"in e&&Qt(l,e),p(e)},v=(e,t=!0)=>{a=e,t&&p(e)},m=()=>{a=void 0},_=At({addListener:e=>{Qt(c,e)}}),h=At({addListener:e=>{Qt(u,e)}}),b=At({addListener:e=>{Qt(d,e)}}),M=()=>{g(),e.send("port.message",At({response_id:n,disconnect:!0}))};let y=At(r?{postMessage:f,connectMessage:v,stopReconnecting:m,onMessage:_,onDisconnect:h,onReconnect:b,disconnect:M}:{postMessage:f,onMessage:_,onDisconnect:h,disconnect:M});return o[n]=At({message:e=>{if(s&&(e=>"ack"in e)(e)){const{messageId:n}=e;(e=>{
if(!e)return void t.warn("PortMessaging: no message id in ack message");if(a&&a.messageId===e)return;let n=-1;Xt(l,((t,o)=>t.messageId===e&&(n=o,!0))),-1!==n?(en(Jt(l,0,n),(e=>t.warn(`PortMessaging: message ${e.messageId} was not ack'ed!`,e))),l=Jt(l,n+1)):t.warn(`PortMessaging: no one is waiting for ${e}`)})(n)}c&&en(c,(t=>t(e)))},disconnect:()=>{if(a&&r)return i(r,n),v(a),s&&en(l,(e=>p(e))),void(d.length&&en(d,(e=>e())));u.length&&en(u,(e=>e())),g()}}),y},i=(e,t)=>{
n.first.send("port.message",At({response_id:t,connect:!0,destination:e}))};return At({message:(e,n)=>{let i;if(e.connect){if(!e.destination||!e.response_id)throw"invalid message";r&&r(e.destination,s(n,e.response_id))}else{if(!e.response_id)throw"invalid message";if(!(i=o[e.response_id]))return void t.warn("ports: unknown id",e.response_id,e);e.disconnect?i.disconnect():i.message(e.value)}},connect:function(e,t,o){const r=uo();return i(e,r),s(n.first,r,t?e:void 0,o)},onConnect:At({
addListener:e=>{r=e}})})})(),{bridges:vo}=e,mo=At({});let _o=!0,ho=[];go((()=>{_o=!1;const e=vo.first;en(ho,(({m:t,i:n})=>e.send("console",[t,n]))),ho=[]})),en(["debug","log","info","warn","error"],(e=>{Dt(mo,e,((...t)=>{const n=(e=>{const t=[];return en(e,(e=>{Qt(t,(e=>qt(e))(e))})),t})(t);if(_o)return Qt(ho,At({m:e,i:n}));vo.first.send("console",[e,n])}))}))
;const bo=At(Ot(_t.console)),Mo=At({}),yo=["GM.backgroundControl"],wo=["GM_addElement","GM.addElement","GM_addStyle","GM.addStyle"],Eo=["GM_cookie","GM.cookie"],So=["GM_listValues","GM.listValues","GM_getValue","GM.getValue","GM_getValues","GM.getValues","GM_addValueChangeListener","GM.addValueChangeListener","GM_removeValueChangeListener","GM.removeValueChangeListener","GM_setValue","GM.setValue","GM_setValues","GM.setValues","GM_deleteValue","GM.deleteValue","GM_deleteValues","GM.deleteValues"],Go=["GM_download","GM.download"],Lo=["GM_getResourceText","GM.getResourceText","GM_getResourceURL","GM.getResourceUrl"],Ro=["GM_getTab","GM.getTab","GM_getTabs","GM.getTabs","GM_saveTab","GM.saveTab"],Io=["GM_log","GM.log"],Oo=["GM_notification","GM.notification"],Co=["GM_openInTab","GM.openInTab"],xo=["GM_audio","GM.audio"],ko=["GM_registerMenuCommand","GM.registerMenuCommand","GM_unregisterMenuCommand","GM.unregisterMenuCommand"],To=["GM_setClipboard","GM.setClipboard"],Po=["GM_xmlhttpRequest","GM.xmlHttpRequest"],Ao=["window.close"],Do=["window.focus"],Uo=["window.onurlchange"],$o=["GM_webRequest","GM.webRequest"],jo=At({
encode:e=>Fe(De(e)),decode:e=>Ue(Ve(e))}),Vo=At({encode:e=>{let t="";for(let n=0;n<e.length;n++)t+=Mn(255&Sn(e,n));return qe(t)},decode:e=>Ne(e)}),Fo=e=>{const t=new Qn(e.length);for(let n=0;n<e.length;n++)t[n]=Sn(e,n);return jn(t)},No=e=>ao((t=>{const n=new eo([e]);qo(n).then(t)})),qo=(e,t)=>ao((n=>{const o=new io.FileReader;o.onload=()=>{n(_n(o))},o.onerror=e=>{so.warn(`unable to decode data ${e}`),n("")},t?mn(o,e,t):vn(o,e)})),{bridges:Bo}=e;let Xo=0,Ho=0
;const Wo=At({}),Ko=At({}),Jo=function(e,t,n,o){const r=()=>{Wo[n]&&(Pt(e,this,o),delete Wo[n])};"function"==typeof e&&(Wo[n]=e,0===t?go((()=>r())):Bo.first.send("setTimeout",At({t:t||1}),(()=>r())))},zo=function(e,t,n,o){if("function"==typeof e){const r=Ko[n]=fo.connect("setInterval");r.onMessage.addListener((()=>{Ko[n]&&Pt(e,this,o)})),r.onDisconnect.addListener((()=>Yo(n))),r.postMessage(At({method:"setInterval",t:t||1}))}},Yo=e=>{const t=Ko[e];t&&(t.disconnect(),delete Ko[e])
},Qo=(e,t,...n)=>{const o=uo();return Jo(e,t,o,n),o},Zo=e=>{(e=>{delete Wo[e]})(e)},er=e=>Yo(e),tr=(e,t,...n)=>{const o=++Ho;return t=Tt(t,1),Jo(e,t,o,n),o},nr=(e,t,...n)=>{const o=++Xo;return t=Tt(t,1),zo(e,t,o,n),o};let or;const rr=e=>{if(void 0===or){or=!0;const t="keepAlive",n=fo.connect(t,!0),o=io.location.href;n.onMessage.addListener((()=>{})),n.connectMessage(At({messageId:uo(),method:t,id:e,url:o})),n.onDisconnect.addListener((()=>{r&&er(r),r=null}));let r=((e,t,...n)=>{const o=uo()
;return zo(e,t,o,n),o})((()=>{or?n.postMessage(At({messageId:uo(),method:"keepAlive",url:o})):r&&(n.disconnect(),er(r),r=null)}),2e4)}},sr=t=>{const{contextId:o,bridges:r}=e,s=r.first,i=At({}),a=(e,t)=>Xt(t,(t=>-1!=Zt(e,t))),l=e=>function(){return new gn((t=>t(Pt(e,this,arguments))))},c=(e,t)=>function(...n){const o=[];if(void 0!==t)for(let e=0;e<t;e++)Qt(o,to(n,e)||void 0);return new gn((t=>{Pt(e,this,Yt(o,[t]))}))},u=(e,t)=>{let n;const o=new gn(((o,r)=>{
const s=At({}),i=t.onload,a=t.ontimeout,l=t.onerror;en(yt(t),(e=>{s[e]=t[e]})),s.onerror=function(e){l?(o(e),Pt(l,this,arguments)):r(e)},s.ontimeout=function(e){a?(o(e),Pt(a,this,arguments)):r(e)},s.onload=function(e){o(e),i&&Pt(i,this,arguments)};const c=e(s).abort;!0===n?c():n=c}));return Dt(o,"abort",(()=>{"function"==typeof n?n():n=!0})),o};return At({of:e=>{const r=e.script,d=(()=>{const e=a(r.grant,To),t=(e,t,n)=>{s.send("setClipboard",At({content:e,info:t,id:o,uuid:r.uuid
}),n?()=>n():null)};return At({GM_setClipboard:e?At({value:t}):void 0,"GM.setClipboard":e?At({get:()=>c(t,2)}):void 0})})(),g=(()=>{let t=[];const n=e.storage;let s=0,i=null;const c=a(r.grant,So),u=(e,t)=>{if("string"!=typeof e)return t;{const n=yn(e,0,1);switch(e=yn(e,1),n){case"b":return"true"===e;case"n":return Kn(e);case"x":try{return jo.decode(Vo.decode(e))}catch(t){return e}case"o":try{return Bt(e)}catch(e){so.log(`values: parseValueFromStorage: ${e}`)}return t;case"u":return;default:
return e}}},d=(e,n,o,r)=>{n!=o&&en(t,(t=>{if(t&&t.key==e&&t.cb)try{t.cb(e,u(n),u(o),r)}catch(t){so.warn(`values: change listener of "${e}" failed with: ${t.message}`)}}))},g=(e,t)=>{i&&i.postMessage(At({messageId:uo(),method:"saveStorageKey",uuid:r.uuid,key:e,value:n.data[e],removed:t,id:o,ts:n.ts}))};c&&(rr(o),i=fo.connect("values",!0,!0),i.onDisconnect.addListener((()=>{so.warn("values: port disconnected"),i=null})),i.onMessage.addListener((e=>{if("ack"in e)return;const{storage:t,removed:o}=e
;if(!t)return;const r=t,s=yt(r);o&&Qt(s,o),en(s,(e=>{const t=n.data[e],o=r[e];void 0===o?delete n.data[e]:n.data[e]=o,d(e,t,o,!0)}))})),i.connectMessage(At({messageId:uo(),method:"addStorageListener",uuid:r.uuid,id:o})));const p=(e,t)=>u(n.data[e],t),f=e=>{const t=At({});let o=e;if(o||(o=yt(n.data)),Ct(o))en(o,(e=>{e in n.data&&(t[e]=p(e))}));else{const e=o;en(yt(e),(n=>{t[n]=p(n,e[n])}))}return t},v=()=>yt(n.data),m=(e,n)=>{const o=++s,r=At({id:o,key:e,cb:n});return Qt(t,r),o},_=e=>{
t=Kt(t,(t=>t.id!==e))},h=(e,t)=>{const o=n.data[e];n.ts=Hn(),n.data[e]=(e=>{const t=typeof e;let n,o=yn(t,0,1);switch(t){case"object":try{n=o+qt(e)}catch(e){return void so.log(e)}break;case"function":case"symbol":case"bigint":o="u",n=o+void 0;break;case"string":case"number":case"undefined":case"boolean":n=o+e;break;default:n=t}return n})(t),g(e),d(e,o,n.data[e],!1)},b=e=>{const t=yt(e);en(t,(t=>{h(t,e[t])}))},M=e=>{const t=n.data[e];n.ts=Hn(),delete n.data[e],g(e,!0),d(e,t,n.data[e],!1)},y=e=>{
Ct(e)?en(e,(e=>{M(e)})):so.warn("values: removes: names is not an array")};return At({GM_getValue:c?At({value:p}):void 0,"GM.getValue":c?At({get:()=>l(p)}):void 0,GM_getValues:c?At({value:f}):void 0,"GM.getValues":c?At({get:()=>l(f)}):void 0,GM_listValues:c?At({value:v}):void 0,"GM.listValues":c?At({get:()=>l(v)}):void 0,GM_addValueChangeListener:c?At({value:m}):void 0,"GM.addValueChangeListener":c?At({get:()=>l(m)}):void 0,GM_removeValueChangeListener:c?At({value:_}):void 0,
"GM.removeValueChangeListener":c?At({get:()=>l(_)}):void 0,GM_setValue:c?At({value:h}):void 0,"GM.setValue":c?At({get:()=>l(h)}):void 0,GM_setValues:c?At({value:b}):void 0,"GM.setValues":c?At({get:()=>l(b)}):void 0,GM_deleteValue:c?At({value:M}):void 0,"GM.deleteValue":c?At({get:()=>l(M)}):void 0,GM_deleteValues:c?At({value:y}):void 0,"GM.deleteValues":c?At({get:()=>l(y)}):void 0})})(),p=(()=>{const e=a(r.grant,Uo),t=(()=>{let e=[],t=null;var s;return At({register:(n,s)=>ao((i=>{
if(n&&!(Zt(e,n)>-1))if(Qt(e,n),t)i();else{let n=i;rr(o),t=fo.connect("onurlchange",!0),t.onMessage.addListener((t=>{if(n&&(n(),n=void 0),"ack"in t)return;const{url:o}=t;if(!o)return;const r=At({url:o});en(e,(e=>{Pt(e,s,[r])}))})),t.connectMessage(At({messageId:uo(),method:"observeUrlChanges",uuid:r.uuid,id:o}))}})),unregister:(s=n((function*(n){let o;n&&(o=Zt(e,n))>-1&&(e=Ht(e,o,1).result),yield null,t&&0===e.length&&(t.disconnect(),t=null)})),function(e){return s.apply(this,arguments)})})})()
;return At({"window.onurlchange":e?At({value:t}):void 0})})(),f=(()=>{const e=a(r.grant,xo);let t=[],i=null;const l=(e,n)=>{if(Qt(t,e),i)n&&n();else{let e=n;rr(o),i=fo.connect("onaudiostatechange",!0),i.onMessage.addListener((n=>{if(e&&(e(),e=void 0),"ack"in n)return;const o=At({});"muted"in n&&(o.muted=n.muted),"audible"in n&&(o.audible=n.audible),en(t,(e=>{try{Pt(e,void 0,[o])}catch{}}))})),i.connectMessage(At({messageId:uo(),method:"observeAudioStateChanges",uuid:r.uuid,id:o}))}},c=(e,o)=>{
n((function*(){let n;e&&(n=Zt(t,e))>-1&&(t=Ht(t,n,1).result),yield null,i&&0===t.length&&(i.disconnect(),i=null),o&&o()}))()},u=(e,t)=>At({action:e,uuid:r.uuid,details:t}),d=At({setMute:(e,t)=>{s.send("audio",u("setMute",e),t?e=>{"error"in e?(so.warn("audio: "+e.error),t(e.error)):"success"in e?t():(so.warn("audio: unexpected response"),t("unexpected response")),t()}:null)},getState:e=>{s.send("audio",u("getState",void 0),e?t=>{"error"in t?(so.warn("audio: "+t.error),e()):"muted"in t?e(At({
isMuted:!!t.muted,muteReason:t.muted?t.muted:void 0,isAudible:t.audible})):(so.warn("audio: unexpected response"),e())}:null)},addStateChangeListener:(e,n)=>{if(e&&!(Zt(t,e)>-1))return l(e,n)},removeStateChangeListener:c});return At({GM_audio:e?At({get:()=>{const e=(e,...t)=>Pt(d[e],void 0,t);return en(yt(d),(t=>{Dt(e,t,d[t])})),e}}):void 0,"GM.audio":e?At({get:()=>{const e=At({});return en(yt(d),(n=>{e[n]=e=>{return o=n,r=e,new gn(((e,n)=>{if("setMute"==o){const t=r;d[o](t,(o=>{o?n(o):e(t)}))
}else if("getState"==o)d[o]((t=>{e(t)}));else if("addStateChangeListener"==o){const o=r;if(!o||Zt(t,o)>-1)return n();l(o,(()=>e()))}else"removeStateChangeListener"==o?c(r,(()=>e())):n("unknown method")}));var o,r}})),e}}):void 0})})(),v=(()=>{const e=a(r.grant,Lo),t=e=>{for(let t=0;t<r.resources.length;t++){const n=r.resources[t];if(n.name==e){if(n.error)so.warn("@resource: "+n.error);else try{if("string"==typeof n.content)return jo.decode(n.content)}catch(e){}return""}}return null},n=e=>{
for(let t=0;t<r.resources.length;t++){const n=r.resources[t];if(n.name==e){if(n.error)so.warn("@resource: "+n.error);else if("string"==typeof n.content){try{return`data:${n.meta||"application/octet-stream"};base64,${Vo.encode(n.content)}`}catch(e){}return n.url}return""}}return null};return At({GM_getResourceText:e?At({value:t}):void 0,"GM.getResourceText":e?At({get:()=>l(t)}):void 0,GM_getResourceURL:e?At({value:n}):void 0,"GM.getResourceUrl":e?At({get:()=>l(n)}):void 0})})(),m=(()=>{
const e=a(r.grant,Ro),t=(e,t)=>{s.send("tabs",At({action:"set",uuid:r.uuid,tab:e}),t?()=>t():null)},n=e=>{s.send("tabs",At({action:"get",uuid:r.uuid}),e?t=>{e(t||At({}))}:null)},o=e=>{s.send("tabs",At({action:"list",uuid:r.uuid}),e?t=>{e(t||At({}))}:null)};return At({GM_saveTab:e?At({value:t}):void 0,"GM.saveTab":e?At({get:()=>c(t,1)}):void 0,GM_getTab:e?At({value:n}):void 0,"GM.getTab":e?At({get:()=>c(n)}):void 0,GM_getTabs:e?At({value:o}):void 0,"GM.getTabs":e?At({get:()=>c(o)}):void 0})
})(),_=(()=>{const e=a(r.grant,Po),s=e=>{const s=an(e);let a=!1,l=()=>{a=!0};const c=(e,t)=>{t=t||At({}),e&&Qo((()=>{Et(t,i),Pt(e,t,[t])}),1)},u=s.url;"object"==typeof u&&u.href&&(s.url=u.href);const d=(e,t)=>{const n=ln(e);if("Blob"===n||"File"===n){const o=e;qo(o).then((e=>{t(At({type:n,value:e,meta:o.type,name:o.name,lastModified:o.lastModified}))}))}else if("ArrayBuffer"===n)No(e).then((e=>{t(At({type:"Blob",value:e,meta:"application/octet-stream"}))}));else if("Uint8Array"===n){
const n=jn(e);No(n).then((e=>{t(At({type:"Blob",value:e,meta:"application/octet-stream"}))}))}else if("FormData"===n){const n=e,o=n.keys();let r;const s=At({}),i=[];for(;!(r=o.next()).done;)Qt(i,r.value);const a=()=>{if(i.length){const e=Wt(i);let t=n.getAll(e);"[]"!==yn(e,-2)&&(t=to(t,0)),d(t,(t=>{s[e]=t,a()}))}else t(At({type:"FormData",value:s}))};a()}else if("URLSearchParams"===n)t(At({type:"URLSearchParams",value:$n(e)}));else if("Array"===n||"Object"===n){const o=e;let r,s,i=0,a=0
;if("Object"===n){const e=yt(o);s=t=>t<e.length?e[t]:null,r=At({})}else s=e=>e<o.length?e:null,r=[];const l=()=>{const e=s(i);null===e?t(At({type:n,value:r})):d(o[e],(t=>{r[e]=t,i++,a++<1024?l():(a=0,Qo(l,1))}))};l()}else t(At({value:e,type:"raw"}))},g=(e,t,n,o,r)=>{let s;if(n)"stream"==o&&(s=n);else if("arraybuffer"==o)s=t||Fo(e||"");else if("blob"==o)s=new io.Blob([t||Fo(e||"")],At({type:r}));else if("json"==o)s=Bt(e||"");else if("document"==o){
const t=new io.DOMParser,n=["application/xhtml+xml","application/xml","image/svg+xml","text/html","text/xml"];let o=to(nn(r||"text/xml",";"),0);-1==Zt(n,o)&&(o="text/xml");try{s=On(t,e||"",o)}catch(e){s=null}}else s=e||(t?(e=>{let t="";const n=new Qn(e);for(let e=0;e<n.length;e+=32687)t+=Pt(Mn,null,Vn(n,e,e+32687));return t})(t):"");return s};return(e=>{if(s.url){const t=yn(s.url,0,5);if(-1!=Zt(["data:","blob:"],t))return e()}if(!s.data)return e();d(s.data,(t=>{s.binary&&(t.type="Blob"),
s.data=t,s.data_type="typified",e()}))})((()=>{if(a)return a=!1,void c(s.onabort);let e,i,u,d=fo.connect("xhr"),p=[],f=!1;const{method:v,url:m,redirect:_,headers:h,cookie:b,binary:M,nocache:y,revalidate:w,timeout:E,context:S,responseType:G,overrideMimeType:L,anonymous:R,cookiePartition:I,fetch:O,user:C,password:x,data:k,data_type:T}=s,P=At({method:v,url:m,redirect:_,headers:h,cookie:b,binary:M,nocache:y,revalidate:w,timeout:E,responseType:G,overrideMimeType:L,anonymous:R,cookiePartition:I,
fetch:O,user:C,password:x,data:k,data_type:T});if(P.headers){const e=P.headers;en(yt(e),(t=>{"cookie"===Gn(t)&&(P.cookie=`${e[t]}`,delete e[t])}))}const A=At({messageId:uo(),method:"xhr",details:P,callbacks:At({onloadstart:!!s.onloadstart,onload:!!s.onload,ondone:!!s.onloadend,onreadystatechange:!!s.onreadystatechange,onerror:!0,onabort:!!s.onabort,ontimeout:!!s.ontimeout,onprogress:!!s.onprogress,onuploadprogress:!(!s.upload||!s.upload.onprogress),onpartial:!0}),id:o,location:io.location.href,
uuid:r.uuid,no_blob:"js"==t.sandboxMode});let D,U,$,j;d.postMessage(A);const V=G?Gn(G):"";let F,N=0,q=0;const B=function(){var t=n((function*(t){if(t&&(u||void 0!==e||void 0!==i)){if(L?j=L:t&&(j=(e=>{const t=At({});return e&&en(nn(e,"\n"),(e=>{const n=nn(e,":");if(n.length<2)return;const o=to(n,0);if(!o)return;const r=zt(Jt(n,1),":");t[Gn(En(o))]=En(r||"")})),t})(t.responseHeaders)["content-type"]),D=e,u)$=u.stream;else if(i){const e=i;if(U=e.buffer,-1==Zt(["blob","arraybuffer"],V)&&!D){let t
;Xt([j,e.type],(e=>t=((e,t,n,o)=>{const r=wn(e,"charset=");if(-1==r)return;const s=yn(e,r+8),i=wn(s,";");return-1==i?o&&o.optionalEnd?s:void 0:yn(e,r+8,i)})(Gn(e||""),0,0,At({optionalEnd:!0}))));const n=new eo([U]);F=qo(n,t),D=yield F}F=void 0}else F&&(yield F);e=i=void 0}if(D||$||U){t.responseType=G,en(["response_data"],(e=>delete t[e]));const e=At({response:()=>g(D,U,$,V,j||"binary/octet-stream"),responseText:()=>g(D,U,$,"text",j),responseXML:()=>g(D,U,$,"document",j||"text/xml")})
;en(yt(e),(n=>{Gt(t,n,At({get(){try{return e[n]()}catch(e){so.warn(`${v}:`,e)}}}))}))}}));return function(e){return t.apply(this,arguments)}}(),X=[],H=function(){var e=n((function*(e){e&&Qt(X,e);{const e=Wt(X);e&&e()}}));return function(t){return e.apply(this,arguments)}}();"stream"===V&&H(n((function*(){u=yield ao((e=>{const t=new io.ReadableStream(At({start:n=>{Qo((()=>e(At({stream:t,ctrl:n}))),0)},cancel:()=>{u&&(u.canceled||l(),u.canceled=!0)}}))}))})));const W=function(){
var t=n((function*(t){if(!("ack"in t))if(t.onpartial){const n=t.data,o=n,r=o.partial,s=n.nada;if(u){if(u.canceled)return;const e=hn||((e,t)=>e.enqueue(t));if(void 0!==r)e(u.ctrl,r);else if(void 0!==s){const t=new Qn(s.buffer);e(u.ctrl,t)}else so.error(`${v}:`,"data message without data?!")}else{let t;r&&Qt(p,r),s&&(t=s),void 0!==o.index&&o.index!==o.length-1||(p.length&&(e=zt(p,""),p=[]),i=t)}}else{const e=t.data;if(N=e.readyState||N,q=e.status||q,S&&(e.context=S),t.onload)yield B(e),
c(s.onreadystatechange,e),c(s.onload,e);else if(t.onreadystatechange)yield B(e),4!=e.readyState&&c(s.onreadystatechange,e);else if(t.onerror)t.exception&&so.error(t.exception),c(s.onerror,e);else if(t.onabort)c(s.onabort,e);else if(t.ondone)f=!0,u&&!u.canceled&&(bn||(e=>e.close()))(u.ctrl),yield B(e),c(s.onloadend,e);else if(t.onloadstart)u&&(yield B(e)),c(s.onloadstart,e);else if(t.onuploadprogress)s.upload&&c(s.upload.onprogress,e);else{
const n=to(Kt(["onprogress","ontimeout"],(e=>!!t[e])),0)||"onerror";c(s[n],e)}}}));return function(e){return t.apply(this,arguments)}}();d.onMessage.addListener((e=>H((()=>W(e))))),d.onDisconnect.addListener((()=>{f||c(s.onerror,At({readyState:N,status:q,error:"background shutdown"})),d=null})),l=()=>{d&&d.postMessage(At({messageId:uo(),cancel:!0}))}})),At({abort:()=>{l()}})},i=(()=>{const e=At({toString:()=>"[object Object]",DONE:Fn,HEADERS_RECEIVED:Nn,LOADING:qn,OPENED:Bn,UNSENT:Xn})
;return en(["text","arraybuffer","blob","document","json","stream"],(t=>{e[`RESPONSE_TYPE_${Ln(t)}`]=t})),e})();return en(yt(i),(e=>Dt(s,e,i[e]))),At({GM_xmlhttpRequest:e?At({value:s}):void 0,"GM.xmlHttpRequest":e?At({get:()=>{const e=e=>u(s,e);return en(yt(i),(t=>Dt(e,t,i[t]))),e}}):void 0})})(),h=(()=>{let n;const o=()=>{if(!n){
const{script:o}=e,{antifeatures:r,author:s,blockers:i,copyright:a,deleted:l,description_i18n:c,description:u,downloadURL:d,fileURL:g,grant:p,header:f,homepage:v,icon:m,icon64:_,lastModified:h,name_i18n:b,name:M,namespace:y,position:w,resources:E,supportURL:S,system:G,updateURL:L,version:R,webRequest:I,options:{override:{orig_connects:O,orig_excludes:C,orig_includes:x,orig_matches:k},run_at:T,run_in:P,unwrap:A}}=o,{downloadMode:D,inIncognitoContext:U,relaxedCsp:$,isFirstPartyIsolation:j,container:V,sandboxMode:F,userAgent:N,version:q}=t,B=L||g,X=At({
antifeatures:r,author:s,blockers:i,connects:O,copyright:a,deleted:l,description_i18n:c,description:u,downloadURL:d,excludes:C,fileURL:g,grant:p,header:f,homepage:v,icon:m,icon64:_,includes:x,lastModified:h,matches:k,name_i18n:b,name:M,namespace:y,options:o.options,position:w,resources:E,"run-at":T,"run-in":P,supportURL:S,system:G,unwrap:A,updateURL:L,version:R,webRequest:I}),H=At({downloadMode:D,isFirstPartyIsolation:j,isIncognito:U,relaxedCsp:$,sandboxMode:F,container:V?At({id:V}):void 0,
script:X,scriptHandler:"Tampermonkey",scriptMetaStr:o.header,scriptUpdateURL:B,scriptWillUpdate:!!B,userAgentData:N,version:q});n=H}return Bt(qt(n))};return At({GM_info:At({get:o}),"GM.info":At({get:o})})})(),b=(()=>{const e=a(r.grant,$o);let t=null;const n=(e,n)=>{const s=()=>{t==i&&(t=null),i=null};t&&t.disconnect(),rr(o);let i=t=fo.connect("webRequest",!0);return n&&i.onMessage.addListener((e=>{"ack"in e||n(e.type,e.message||"ok",e.details)})),i.onDisconnect.addListener(s),
i.connectMessage(At({messageId:uo(),rules:e,uuid:r.uuid})),At({abort:()=>{i&&i.disconnect(),s()}})};return At({GM_webRequest:e?At({value:n}):void 0,"GM.webRequest":e?At({get:()=>l(n)}):void 0})})(),M=(()=>{const e=a(r.grant,ko);let t=0;const n=At({}),o=At({}),s=(e,s,a)=>{if("string"!=typeof e)throw"invalid name";const{accessKey:l,autoClose:c,title:u,id:d}="string"==typeof a?At({accessKey:a}):a||At({}),g=void 0!==d?d:++t,p=n[g],f=p||fo.connect("registerMenuCommand",!0);return o[g]=s,
p||(f.onMessage.addListener((e=>{if(!("ack"in e)&&"run"===e.method){const t=o[g];if(!t)return;const n=e.event,r=n?n.keyCode?new zn("keypress",n):new Yn("click",e.event):void 0;Qo((()=>t(r)),1)}})),f.onDisconnect.addListener((()=>{i(g)})),n[g]=f),f.connectMessage(At({messageId:uo(),name:e,uuid:r.uuid,accessKey:l,autoClose:c,title:u,id:`${g}`})),g},i=e=>{delete o[e];const t=n[e];t&&(t.disconnect(),delete n[e])};return At({GM_registerMenuCommand:e?At({value:s}):void 0,
"GM.registerMenuCommand":e?At({get:()=>l(s)}):void 0,GM_unregisterMenuCommand:e?At({value:i}):void 0,"GM.unregisterMenuCommand":e?At({get:()=>l(i)}):void 0})})(),y=(()=>{const e=a(r.grant,Oo),t=At({}),n=At({}),o=(e,o,s,i)=>{let a,l,c=null,u=i||null;const d=e=>zt([e?`tag-${e}`:uo(),r.uuid],"#");if("object"==typeof e){const t=an(e),{timeout:n,text:s,image:i,title:g,highlight:p,silent:f,url:v,tag:m,ondone:_,onclick:h}=t;l=d(m),a=At({id:l,timeout:n,text:s,image:i||r.icon64||r.icon||void 0,
title:g||r.name,highlight:p,silent:f,url:v,tag:m}),"ondone"in t&&(c=_),"onclick"in t&&(u=h),"function"==typeof o&&(c=o)}else l=d(),a=At({id:l,text:e,title:"string"==typeof o?o:r.name,image:s||r.icon64||r.icon||void 0});null!==u&&(a.onclick=u),null!==c&&(a.ondone=c),((e,o)=>{const s=an(o),{text:i,title:a,tag:l,url:c,image:u,highlight:d,silent:g,timeout:p,onclick:f,ondone:v}=s;if("onclick"in s&&(t[e]=f),"ondone"in s&&(n[e]=v),i||d){const o="notification",s=fo.connect(o,!0)
;s.onMessage.addListener((o=>{if("ack"in o)return;const{clicked:r}=o;let f=!1;const v=At({text:i,title:a,tag:l,url:c,image:u,highlight:d,silent:g,timeout:p,preventDefault:()=>{f=!0}}),m=t[e],_=n[e];r&&(m&&m(v),s.postMessage(At({messageId:uo(),canceled:f}))),_&&_(!0===r,v),s.disconnect(),delete t[e],delete n[e]})),s.connectMessage(At({messageId:uo(),method:"notification",id:e,uuid:r.uuid,text:i,title:a,tag:l,url:c,image:u,highlight:d,silent:g,timeout:p}))
}else so.warn("GM_notification: neither a message text nor highlight options were given!")})(l,a)};return At({GM_notification:e?At({value:o}):void 0,"GM.notification":e?At({get:()=>(e,t,n,r)=>{let s;return s="object"==typeof e?e:At({text:e,title:t,image:n,onclick:r}),new gn((e=>{const t=At({});en(yt(s),(e=>{t[e]=s[e]}));const n=t.ondone;t.ondone=function(t,o){n&&Pt(n,this,[t,o]),Pt(e,this,[t])},o(t)}))}}):void 0})})(),w=(()=>{const e=a(r.grant,Eo),t=(e,t)=>At({action:e,uuid:r.uuid,
location:io.location.href,details:t}),n=At({set:(e,n)=>{s.send("cookie",t("set",e),n?e=>{n(e.error)}:null)},delete:(e,n)=>{s.send("cookie",t("delete",e),n?e=>{n(e.error)}:null)},list:(e,n)=>{s.send("cookie",t("list",e),n?e=>{n(e.cookies,e.error)}:null)}});return At({GM_cookie:e?At({get:()=>{const e=(e,t,o)=>(n[e]||(()=>{}))(t,o);return en(yt(n),(t=>{Dt(e,t,n[t])})),e}}):void 0,"GM.cookie":e?At({get:()=>{const e=At({});return en(yt(n),(t=>{e[t]=e=>((e,t)=>new gn(((o,r)=>{if("list"==e){
const s=t||At({});n[e](s,((e,t)=>{t?r(t):o(e)}))}else if("set"==e){const s=t;n[e](s,(e=>{e?r(e):o(void 0)}))}else{const s=t;n[e](s,(e=>{e?r(e):o(void 0)}))}})))(t,e)})),e}}):void 0})})(),E=(()=>{const e=a(r.grant,Go),t=(e,t)=>{const n=ln(e);return-1==Zt(["String","Blob","File"],n)?e:At({url:e,name:t,mode:void 0,headers:void 0,saveAs:void 0,conflictAction:void 0,onprogress:void 0,onload:void 0,ondone:void 0,ontimeout:void 0,onerror:void 0})},n=(e,n)=>{const s=t(e,n),i=(e,t)=>{t=t||At({}),
e&&Qo((()=>{Pt(e,t,[t])}),1)},{url:a,name:l,mode:c,headers:u,saveAs:d,conflictAction:g}=s;let p;rr(o);let f=fo.connect("download",!0);const v=()=>{f&&f.stopReconnecting()};f.onMessage.addListener((e=>{if(!("ack"in e)){f&&void 0===p&&(p=e.id,f.connectMessage(At({messageId:uo(),method:"download",uuid:r.uuid,id:p}),!1));try{e.load?(s.onload&&i(s.onload,e.data),v()):e.progress?s.onprogress&&i(s.onprogress,e.data):e.timeout?(s.ontimeout&&i(s.ontimeout,e.data),v()):(s.onerror&&i(s.onerror,e.data),v())
}catch(e){so.log("env: Error: TM_download - ",e,s)}}})),f.onDisconnect.addListener((()=>f=null));const m=At({messageId:uo(),details:At({url:a,name:l,mode:c,headers:u,conflictAction:g,saveAs:d}),uuid:r.uuid});return f.postMessage(m),At({abort:()=>{f&&f.postMessage(At({uuid:r.uuid,cancel:!0}))}})};return At({GM_download:e?At({value:n}):void 0,"GM.download":e?At({get:()=>(e,o)=>u(n,t(e,o))}):void 0})})(),S=(()=>{const e=a(r.grant,Co),t=(e,t)=>{const n="openInTab";let s,i,a=!1,l=null;const c=(()=>{
const e=[];return At({run:t=>{if(t&&Qt(e,t),s)for(;e.length;)Wt(e)()}})})();rr(o);let u=fo.connect(n,!0);const d=()=>{u&&u.postMessage(At({messageId:uo(),close:!0}))};u.onMessage.addListener((e=>{"ack"in e||(e.tabId?a?d():(u&&void 0===s&&u.connectMessage(At({messageId:uo(),method:n,uuid:r.uuid,tabId:e.tabId}),!1),s=e.tabId,c.run()):e.name?i=e.name:e.closed&&(a=!0,l&&(l(),l=null),u&&u.stopReconnecting()))})),u.onDisconnect.addListener((()=>u=null)),u.postMessage(At({messageId:uo(),method:n,url:e,
location:io.location.href,options:t,uuid:r.uuid}));const g=At({});return St(g,At({close:At({value:()=>{a?so.warn("env: attempt to close already closed tab!"):d()}}),focus:At({value:()=>{u&&u.postMessage(At({messageId:uo(),focus:!0}))}}),closed:At({get:()=>a}),onclose:At({get:()=>l,set:e=>{l=e}}),name:At({get:()=>i,set:e=>{c.run((()=>{u&&u.postMessage(At({messageId:uo(),name:e}))}))}})})),g};return At({GM_openInTab:e?At({value:t}):void 0,"GM.openInTab":e?At({get:()=>l(t)}):void 0})})(),G=(()=>{
const e=a(r.grant,Ao);return At({"window.close":e?At({value:e=>{s.send("closeTab",At({uuid:r.uuid}),e?()=>e():null)}}):void 0})})(),L=At({navigate:At({value:(e,t)=>{s.send("navigateTab",At({uuid:r.uuid,url:e}),t?()=>t():null)}})}),R=(()=>{const e=a(r.grant,Do);return At({"window.focus":e?At({value:e=>{s.send("focusTab",At({uuid:r.uuid}),e?()=>e():null)}}):void 0})})(),I=(()=>{const e=a(r.grant,Io),t=function(...e){Pt(so.log,this,e)};return At({GM_log:e?At({value:t}):void 0,"GM.log":e?At({
get:()=>l(t)}):void 0})})(),O=({root:e,tag:t,properties:n,cb:o})=>{const i=uo(),a=At({tag:t,properties:n,id:i,uuid:r.uuid});s.send("addElement",a,e,o?()=>o():null);const l=oo.getElementById(i),c=n?n.id:void 0;return void 0!==c&&Tn(l,"id",c),l},C=(()=>{const e=a(r.grant,wo),t=(e,t)=>O(At({root:void 0,tag:"style",properties:At({textContent:e}),cb:t}));return At({GM_addStyle:e?At({value:t}):void 0,"GM.addStyle":e?At({get:()=>l(t)}):void 0})})(),x=(()=>{const e=a(r.grant,wo),t=(e,t,n,o)=>{
let r,s,i,a;return"string"==typeof e?(s=e,i=t,a=n):(r=e,s=t,i=n,a=o),i&&(i=At(i)),O(At({root:r,tag:s,properties:i,cb:a}))};return At({GM_addElement:e?At({value:t}):void 0,"GM.addElement":e?At({get:()=>l(t)}):void 0})})(),k=(()=>{const e=a(r.grant,yo),t=(e,t)=>{const n="backgroundControl",s=fo.connect(n);let i=!1;const a="restart"===e.action||void 0;s.onMessage.addListener((e=>{if("ack"in e)return;i=!0;const n=e?e.error:void 0;n&&so.warn(n),t&&t(n),s.disconnect()})),s.postMessage(At({
messageId:uo(),method:n,id:o,uuid:r.uuid,restart:a})),a&&(or=!1),s.onDisconnect.addListener((()=>{!i&&t&&t(a?void 0:"port disconnected for unknown reason"),i=!0}))};return At({"GM.backgroundControl":e?At({get:()=>l(t)}):void 0})})(),T=At({...x,...C,...G,...L,...w,...E,...R,...h,...I,...M,...y,...S,...v,...d,...m,...p,...f,...g,...b,..._,...k});return i[e.script.uuid]=i[e.script.uuid]||T,i[e.script.uuid]}})},ir=(e,t,o,r,s,i)=>{const a=(e,t,n,o,r)=>{const s=t[n],a=typeof s
;return o&&"string"===a?t[n]=()=>i(s,r):r&&"function"===a&&(t[n]=function(){return Pt(s,r,arguments)}),Pt(e,_t,t)},l=function(){var e=n((function*(e,t,n,o){const r=At({attrName:"null",newValue:"null",prevValue:"null",eventPhase:An,target:_t.document,relatedNode:_t.document,srcElement:_t.document});yield null,n||(yield null),"load"===e&&(yield null),((e,t,n,o)=>{const r=At({bubbles:!0,cancelBubble:!1,cancelable:!1,clipboardData:void 0,currentTarget:null,defaultPrevented:!1,eventPhase:0,
newValue:null,prevValue:null,relatedNode:null,returnValue:!0,srcElement:null,target:null,timeStamp:Hn()}),s="string"==typeof n?()=>i(n,o):n,a=new Event(e);en(yt(r),(e=>{Dt(a,e,r[e])})),en(yt(t),(e=>{Dt(a,e,t[e])})),Pt(s,o,[a])})(e,r,t,o)}));return function(t,n,o,r){return e.apply(this,arguments)}}();let c=!0;go((()=>c=!1));const u=At({}),d=e=>!!("object"==typeof e&&null!==e?e.capture:e),g=(e,r,s)=>{let i,g;null===r||("object"==typeof r?(i=function(){var e=n((function*(e){const t=r.handleEvent
;"function"==typeof t&&Pt(t,r,[e])}));return function(t){return e.apply(this,arguments)}}(),g=r):(i=r,g=void 0));const f=d(s);let m,_;if(void 0!==i&&c&&((m="DOMContentLoaded"==e)||"load"==e)){const n=xn(_t.document);if(m&&("complete"==n||"interactive"===n)&&"document-idle"!=t||!m&&"complete"==n)return void l(e,i,f,v)}const h="urlchange"==e?o["window.onurlchange"]:void 0;if(void 0===i);else if("string"!=typeof i){const t=`${e}-${f}`;u[t]=u[t]||[];const n=function(...t){
return"object"==typeof s&&s.once&&p(e,r,s),Pt(i,this===_t||this===ht?v:this,t)},o=At({listener:i,filter:n,object:g});if(Qt(u[t],o),_=n,h)return void h.value.register(n)}else{if(h)return void so.warn("env: urlchange listener must be a function!");_=i}return a(io.addEventListener,[e,_,s],1,!0)},p=(e,t,n)=>{let r,s;null===t||("object"==typeof t?s=t:r=t);const i="urlchange"==e?o["window.onurlchange"]:void 0,l=d(n),c=`${e}-${l}`,g=u[c]&&Kt(u[c],(e=>e.object?e.object===s:e.listener===r))
;if(g&&g.length){let t;if(en(g,(o=>{if(i)i.value.unregister(o.filter);else try{a(io.removeEventListener,[e,o.filter,n],1,!0)}catch(o){t=o}const r=Zt(u[c],o);u[c]=Ht(u[c],r,1).result})),u[c].length||delete u[c],t)throw t}else if(void 0!==r)return a(io.removeEventListener,[e,r,n],1,!0)},f=At({CDATA:At({value:function(e){this.src=e,this.toString=function(){return this.src},this.toXMLString=this.toString}}),uneval:At({value:e=>{try{return`\\$1 = ${qt(e)};`}catch(e){so.log(e)}}}),define:At({
value:void 0}),module:At({value:void 0}),exports:At({value:void 0}),setTimeout:At({value:(...e)=>a(tr,e,0,!0,v)}),setInterval:At({value:(...e)=>a(nr,e,0,!0,v)}),close:(()=>{const e=o["window.close"];return e?At({get:()=>_t==_t.top?t=>e.value(t):io.close}):void 0})(),focus:(()=>{const e=o["window.focus"];return e?At({get:()=>t=>e.value(t)}):void 0})(),onurlchange:o["window.onurlchange"]?(()=>{let e=null;return At({get:()=>e,set:t=>{e&&p("urlchange",e),e=t,g("urlchange",e)}})})():void 0,
location:At({set:e=>{const t=o.navigate;t?t.value(e):io.location.href=e}}),name:At({get:()=>_t.name,set:e=>{_t.name=e}}),clearInterval:At({get:()=>er}),clearTimeout:At({get:()=>Zo}),addEventListener:At({value:g}),removeEventListener:At({value:p}),console:(()=>{let e;return At({get:()=>(e||(e=(()=>{const e=At({});return en(Lt(Ae),(t=>{const n=At(bo[t]),o="value"in n?()=>n.value:n.get;Mo[t]=At({get:o,set:n=>{delete e[t],e[t]=n},enumerable:!0,configurable:!0})})),St(e,Mo),e})()),e)})})()});if(!e){
const e=At({window:At({get:()=>v}),globalThis:At({get:()=>v}),cloneInto:At({value:e=>e}),exportFunction:At({value:(e,t,n)=>{const o=n&&Ut(n,"defineAs");return o&&(t[o]=e),e}}),createObjectIn:At({value:(e,t)=>{const n=At({}),o=t&&Ut(t,"defineAs");return o&&(e[o]=n),n}}),undefined:At({get:()=>{}})});Et(f,e)}r&&Et(f,r);const v=s(f);return v};let ar;n((function*(){const t=e.contextId;let r;const{fSend:s,fOnMessage:i,cloneInto:a,pageWindow:l}=e;r=s&&i?lo(At({sendPrefix:"2U",listenPrefix:"2S",send:s,
onMessage:i})):co(At({sendPrefix:"2C",listenPrefix:"2P"})),e.bridges.first=r;const c=Et(e.console,mo);r.init(t);const u=At({});r.setMessageListener((({method:t,args:n})=>{if("commid"==t)r.switchId(n.id),r.send("ack",At({id:n.id}));else if("injectable"==t)p(n.id,(()=>{r.send("ack",At({id:n.id}))})),r.send("injectableack",At({id:n.id}));else if("setForeignAttr"==t)_t[n.attr]=n.value;else if("script"==t){const{id:t,unwrap:o,bundle:s}=n,{script:i}=s,{name:a,uuid:l,options:{run_at:c}}=i;p(t,(t=>{
const r=o?()=>t():()=>Pt(t,((t,n,o,r)=>{const{pageWindow:s,cloneInto:i,exportFunction:a}=e,l=s||_t,{script:c}=t,u=c.options.compat_powerful_this,d=-1!==Zt(c.grant,"none");ar=ar||sr(n);const g=ar.of(t),p=e=>At({p:m,r:Pt,s:e}),f=At({seed:At({get:()=>p(h),once:!0})}),v=At({}),m=At({GM:v}),_=l&&l;u&&(Dt(f,"GM",At({value:v})),Dt(f,"unsafeWindow",At({value:_}))),d||(m.unsafeWindow=_),en(yt(g),(e=>{const t=yn(e,0,3),n=g[e];if(void 0!==n)if("GM_"===t)m[e]=void 0!==n.get?n.get():n.value,
u&&Dt(f,e,n);else if("GM."===t){const t=on(e,3);n.configurable=n.enumerable=!0,"value"in n?n.writable=!0:"set"in n||(n.set=e=>{delete v[t],v[t]=e}),Gt(v,t,n)}}));const h=d?p(u?m:At({})):ir(d,c.options.run_at,g,f,o,r);return h})(s,n.flags,d,v),[]);"document-start"==c||"context-menu"==c?r():u[l]=r}));const g=`scriptack-${t}`;r.send(g,At({id:t}))}else if("port.message"==t)fo.message(n,r);else if("external.connect"==t)(t=>{const{bridges:n}=e,o=_t,r=Ut(o,"external");if(!r)return
;const s=t?e=>t(e,o,At({cloneFunctions:!0})):e=>e,i=(e,t)=>{n.first.send("external.message",e,t)};try{const e=()=>{const e=At({getVersion:e=>{i(At({method:"getVersion"}),(t=>e(s(t))))},openOptions:(e,t)=>{i(At({method:"openOptions",params:e}),t)},isInstalled:(e,t,n)=>{"function"==typeof t&&(n=t,t=null),n&&i(At({method:"isInstalled",script:At({name:e,namespace:t})}),(e=>n(s(e))))}});return s(e)};St(r,At({Tampermonkey:At({value:e(),configurable:!0})}))}catch(e){}})(a);else if("run"==t){
const{uuid:e}=n,t=Ut(u,e);t?"function"==typeof t&&(t(),delete u[e]):c.warn(`env: missing script "${e}"!`)}}));const{createProxy:d}=((e,t)=>{const n=(e=>{let t=At({});const n=(e,o,r)=>{const s=It(e);s&&s===o||(null!=s&&--r>=0&&n(s,e,r),t=Et(t,Ot(e)))};return n(e,null,5),t})(_t);en(o,(e=>delete n[e]));const r=n;return At({createProxy:n=>{let o=r;const s=e=>{let t,n;const r=(t=Rt(p,e))||(n=o[e]);return At({d:r?At(r):r,l:!!t,w:!!n})},i=e=>{if(!l(e))return!1;if("length"===e)return!0;const t=xt(Kn(e))
;return t>=0&&t<=un&&e===`${t}`},a=e=>"on"===yn(e,0,2),l=e=>"string"==typeof e,c=(e,n)=>{const o=yn(e,2),r=g[o];if(r&&(t.removeEventListener(o,r),delete g[o]),n&&(e=>"function"==typeof e)(n)){const e=(...e)=>Pt(n,t,e);t.addEventListener(o,e),g[o]=e}},u=t=>void 0!==t&&(t===e||t===_t||t===ht),d=At({addEventListener:!0,alert:!0,atob:!0,blur:!0,btoa:!0,cancelAnimationFrame:!0,cancelIdleCallback:!0,captureEvents:!0,clearInterval:!0,clearTimeout:!0,close:!0,confirm:!0,createImageBitmap:!0,
dispatchEvent:!0,dump:!0,fetch:!0,find:!0,focus:!0,getComputedStyle:!0,getDefaultComputedStyle:!0,getSelection:!0,matchMedia:!0,moveBy:!0,moveTo:!0,open:!0,openDatabase:!0,postMessage:!0,print:!0,prompt:!0,queueMicrotask:!0,releaseEvents:!0,removeEventListener:!0,reportError:!0,requestAnimationFrame:!0,requestIdleCallback:!0,resizeBy:!0,resizeTo:!0,scroll:!0,scrollBy:!0,scrollByLines:!0,scrollByPages:!0,scrollTo:!0,setInterval:!0,setResizable:!0,setTimeout:!0,showDirectoryPicker:!0,
sizeToContent:!0,stop:!0,structuredClone:!0,updateCommands:!0,webkitCancelAnimationFrame:!0,webkitRequestAnimationFrame:!0,webkitRequestFileSystem:!0,webkitResolveLocalFileSystemURL:!0});en(yt(d),(e=>{n[e]=n[e]||At({bind:!0})}));const g=At({}),p=At({});Dt(p,Rn,"Window");const f=new Wn(p,At({defineProperty:(e,t,o)=>{const{d:r,l:u}=s(t),d=At(o);return r&&!r.configurable&&(!!r.configurable!=!!d.configurable||!!r.enumerable!=!!r.enumerable)||i(t)?(Gt(u?p:_t,t,d),!1):(Gt(p,t,d),l(t)&&a(t)&&c(t),
delete n[t],!0)},deleteProperty:(e,t)=>{let{d:i,l:u,w:d}=s(t);return!(!i||!i.configurable)&&(u&&(u=delete p[t],l(t)&&a(t)&&c(t)),(d||(i=o[t])&&i.configurable)&&(r===o&&(o=Et(At({}),r)),d=delete o[t]),delete n[t],u||d)},get:(e,t)=>{if("undefined"===t||t===In)return;const o=n[t];if(o){if(o.once&&delete n[t],"value"in o)return o.value;if(o.get)return o.get()}const{d:r,l:a}=i(t)?At({d:Rt(_t,t),l:!1}):s(t);if(r){let e
;const n="value"in r?Ut(r,"value"):(e=Ut(r,"get"))&&"function"==typeof e?a?e():Nt(e,_t)():void 0;return n&&o&&o.bind?Nt(n,_t):a||"event"==t?n:u(n)||"globalThis"===t?f:n}},getOwnPropertyDescriptor:(e,t)=>{let{d:o,l:r}=s(t);if(!o){const e=n[t];if(e)return At({enumerable:!0,configurable:!0,writable:!0,value:e.value,set:e.set,get:e.get});if(!i(t))return;o=Rt(_t,t),r=!1}const a=Et(At({}),o);if(u(a.value)&&(a.value=f),!r){const e=a.get;e&&(a.get=()=>{const t=Nt(e,_t)();return u(t)?f:t}),
a&&!a.configurable&&Gt(p,t,a)}return a},has:(e,t)=>t in p||t in n||t in o,ownKeys:()=>{const e=e=>!(e in o),t=yt(o),n=Kt(yt(Ot(p)),e),r=At({});for(let e=0;"Window"===ln($t(_t,e));e+=1)r[e]=!0;const s=Kt(yt(r),e);return Yt(t,n,s)},preventExtensions:()=>!0,set:(e,t,o)=>{const r=n[t];if(r&&r.set)return r.set(o),!0;const{d:u}=s(t);return!(u&&!u.writable&&!Ut(u,"set")||i(t)||(delete n[t],Dt(p,t,o),l(t)&&a(t)&&c(t,o),0))}}));return f}})})(l,io),g=e=>{r.send("csp",At({src:e}))},p=function(){
var e=n((function*(e,t){Gt(ht,e,At({set:n=>(delete ht[e],po(),t(n)),configurable:!0,enumerable:!1})),go((()=>delete ht[e]))}));return function(t,n){return e.apply(this,arguments)}}(),f=function(){var e=n((function*(e,t,n){p(e,(e=>Pt(e,t,n||[])))}));return function(t,n,o){return e.apply(this,arguments)}}(),v=(e,t)=>t?((e,t)=>{const n=`__p__${uo()}`;f(n,t,void 0),g('window["'+n+'"] = function(){'+e+"};"),delete ht[n]})(e,t):g(e)}))(),po()})()};